import { Calculator, LineChart, WalletCards } from 'lucide-react'

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../lib/shadcn/card'
import { Input } from '../lib/shadcn/input'
import { Badge } from '../lib/shadcn/badge'
import type { DealModel } from '../hooks/backend/diligence'
import { parseDocumentedFacts, type DocumentedFact } from '../utils/evidence'

type PendingArea = 'returns' | 'growth' | 'structure'

const content = {
    returns: { icon: Calculator, title: 'Returns model', description: 'Cash-on-cash return, debt service, IRR, payback, and MOIC.', fields: [['holdPeriodYears', 'Hold period (years)'], ['taxRate', 'Tax rate (decimal)'], ['maintenanceCapex', 'Annual maintenance capex'], ['exitMultiple', 'Exit multiple'], ['exitCosts', 'Exit costs'], ['equityContributionPercent', 'Equity contribution (decimal)'], ['interestRate', 'Interest rate (decimal)'], ['amortizationYears', 'Amortization (years)'], ['sellerNoteAmount', 'Seller note amount']] },
    growth: { icon: LineChart, title: 'Growth scenarios', description: 'Conservative, base, and aggressive revenue, margin, and business-value projections.', fields: [['bearRevenueGrowth', 'Bear revenue growth'], ['baseRevenueGrowth', 'Base revenue growth'], ['bullRevenueGrowth', 'Bull revenue growth'], ['bearEbitdaMargin', 'Bear EBITDA margin'], ['baseEbitdaMargin', 'Base EBITDA margin'], ['bullEbitdaMargin', 'Bull EBITDA margin'], ['bearExitMultiple', 'Bear exit multiple'], ['baseExitMultiple', 'Base exit multiple'], ['bullExitMultiple', 'Bull exit multiple']] },
    structure: { icon: WalletCards, title: 'Deal structure', description: 'Sources and uses, seller financing, earn-outs, rollover equity, and debt capacity.', fields: [['purchasePrice', 'Purchase price'], ['debtAssumed', 'Debt assumed'], ['cashAcquired', 'Cash acquired'], ['workingCapitalRequirement', 'Working-capital requirement'], ['transactionFees', 'Transaction fees']] },
} satisfies Record<PendingArea, { icon: typeof Calculator; title: string; description: string; fields: Array<[keyof DealModel, string]> }>

function getFacts(model?: DealModel) {
    return Object.entries(parseDocumentedFacts(model?.documentedFactsJson)) as Array<[string, DocumentedFact]>
}
function label(value: string) { return value.replace(/_/g, ' ').replace(/\b\w/g, (character) => character.toUpperCase()) }

export default function DealModelPendingCard({ area, model, onChange, onApplyDefaults }: { area: PendingArea; model?: DealModel; onChange?: (field: keyof DealModel, value: string) => void; onApplyDefaults?: (values: Partial<DealModel>) => void }) {
    const item = content[area]; const Icon = item.icon; const facts = getFacts(model)
    const defaults: Array<[keyof DealModel, number]> = area === 'returns' ? [['holdPeriodYears', 5], ['taxRate', 0.25], ['exitMultiple', 4], ['equityContributionPercent', 0.3], ['interestRate', 0.1], ['amortizationYears', 10], ['sellerNoteAmount', 0]] : area === 'growth' ? [['bearRevenueGrowth', 0], ['baseRevenueGrowth', 0.05], ['bullRevenueGrowth', 0.1], ['bearEbitdaMargin', 0.15], ['baseEbitdaMargin', 0.2], ['bullEbitdaMargin', 0.25], ['bearExitMultiple', 3], ['baseExitMultiple', 4], ['bullExitMultiple', 5]] : [['purchasePrice', model?.askingPrice ?? 0], ['transactionFees', model?.askingPrice ? model.askingPrice * 0.01 : 0], ['workingCapitalRequirement', 0]]
    return <Card className="overflow-hidden" data-deal-model-pending><CardHeader className="border-b border-border bg-card/80"><div className="flex items-center gap-2"><Icon className="h-5 w-5 text-primary" /><CardTitle className="text-xl">{item.title}</CardTitle></div><CardDescription>{item.description}</CardDescription></CardHeader><CardContent className="space-y-5 p-5">{area !== 'growth' ? <div className="rounded-lg border border-success/25 bg-success/5 p-4"><div className="flex items-center gap-2"><p className="text-sm font-semibold">Documented project facts</p><Badge variant={facts.length ? 'success' : 'secondary'}>{facts.length ? 'Documented' : 'Not available'}</Badge></div><p className="mt-1 text-xs text-muted-foreground">Confirmed facts are separate from the editable assumptions below.</p>{facts.length ? <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{facts.map(([metric, fact]) => <div key={metric} className="rounded-md border border-border bg-background p-3"><p className="text-xs text-muted-foreground">{label(metric)}</p><p className="mt-1 font-medium">{fact.value?.toLocaleString() ?? 'Not safe to use'} {fact.currency}</p><p className="mt-1 text-xs text-muted-foreground">{fact.period || 'Period not captured'} · {fact.provenance || 'Unverified'}</p></div>)}</div> : null}</div> : null}<div className="rounded-lg border border-primary/25 bg-primary/5 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-semibold">Saved model assumptions</p><p className="mt-1 text-xs text-muted-foreground">These save to the project and never replace evidence.</p></div><button type="button" onClick={() => { const values = Object.fromEntries(defaults) as Partial<DealModel>; if (onApplyDefaults) onApplyDefaults(values); else defaults.forEach(([field, value]) => onChange?.(field, String(value))) }} className="rounded-md border border-primary/30 px-3 py-2 text-xs font-medium text-primary hover:bg-primary/10">Apply illustrative starting assumptions</button></div><p className="mt-2 text-xs text-warning">Illustrative defaults are not industry benchmarks. Review and edit every value before relying on results.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{item.fields.map(([field, fieldLabel]) => <label key={field} className="space-y-1"><span className="text-xs font-medium text-muted-foreground">{fieldLabel}</span><Input inputMode="decimal" value={model?.[field] ?? ''} onChange={(event) => onChange?.(field, event.target.value)} placeholder="Not set" /></label>)}</div></div></CardContent></Card>
}
