import { FileText, Printer, Copy, Check } from 'lucide-react'
import { useState, useCallback } from 'react'

import type { DealModel, ProjectSynthesisItem } from '../hooks/backend/diligence'
import type { SubmissionHistoryItem } from '../utils/submissionHistory'
import { Badge } from '../lib/shadcn/badge'
import { Button } from '../lib/shadcn/button'
import { Card, CardContent, CardHeader, CardTitle } from '../lib/shadcn/card'
import { parseDocumentedFacts } from '../utils/evidence'
import { formatCurrencyValue } from '../utils/aiSubmissionData'
import TruncatedListItem from './TruncatedListItem'

type Props = {
    model: DealModel
    synthesis?: ProjectSynthesisItem
    projectName: string
    documents: SubmissionHistoryItem[]
}

function money(value: number | null | undefined) {
    if (value === null || value === undefined) return '—'
    if (value >= 1_000_000) return `$${(value / 1_000_000).toFixed(1)}M`
    if (value >= 1_000) return `$${(value / 1_000).toFixed(0)}K`
    return `$${value.toFixed(0)}`
}

function buildMemoText(model: DealModel, synthesis: ProjectSynthesisItem | undefined, projectName: string): string {
    const facts = parseDocumentedFacts(model.documentedFactsJson)
    const lines: string[] = []

    lines.push(`DEAL MEMO: ${projectName}`)
    lines.push(`Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`)
    lines.push('')

    lines.push('--- KEY METRICS ---')
    if (facts.revenue?.value) lines.push(`Revenue: $${Number(facts.revenue.value).toLocaleString()}`)
    if (facts.ebitda_sde?.value) lines.push(`EBITDA/SDE: $${Number(facts.ebitda_sde.value).toLocaleString()}`)
    if (model.askingPrice) lines.push(`Asking Price: $${model.askingPrice.toLocaleString()}`)
    if (model.purchasePrice) lines.push(`Purchase Price: $${model.purchasePrice.toLocaleString()}`)
    if (model.purchasePrice && facts.ebitda_sde?.value) {
        lines.push(`Entry Multiple: ${(model.purchasePrice / Number(facts.ebitda_sde.value)).toFixed(1)}x EBITDA`)
    }
    lines.push('')

    if (synthesis) {
        lines.push('--- VERDICT ---')
        lines.push(`Recommendation: ${synthesis.finalRecommendation || 'Pending'}`)
        lines.push(`Risk Level: ${synthesis.finalTrafficLight || synthesis.finalRiskLevel || 'Pending'}`)
        if (synthesis.valuationBaseEstimate && synthesis.valuationBaseEstimate !== '0') {
            lines.push(`Valuation: ${synthesis.valuationLowerBound} – ${synthesis.valuationBaseEstimate} – ${synthesis.valuationUpperBound}`)
            const conf = parseFloat(synthesis.valuationConfidence || synthesis.aiConfidence || '')
            if (Number.isFinite(conf)) {
                const pct = conf <= 1 ? Math.round(conf * 100) : Math.round(conf)
                lines.push(`Confidence: ${pct}%`)
            }
        }
        lines.push('')

        if (synthesis.finalJudgmentSummary) {
            lines.push('--- SUMMARY ---')
            lines.push(synthesis.finalJudgmentSummary)
            lines.push('')
        }

        if (synthesis.redFlags.length > 0) {
            lines.push('--- RED FLAGS ---')
            synthesis.redFlags.forEach(f => lines.push(`• ${f}`))
            lines.push('')
        }

        if (synthesis.negotiationLevers?.length) {
            lines.push('--- NEGOTIATION LEVERS ---')
            synthesis.negotiationLevers.forEach(l => lines.push(`• ${l}`))
            lines.push('')
        }

        if (synthesis.openQuestions?.length) {
            lines.push('--- OPEN QUESTIONS ---')
            synthesis.openQuestions.forEach(q => lines.push(`• ${q}`))
            lines.push('')
        }
    }

    lines.push('---')
    lines.push('Generated by MergeWorks Due Diligence Dashboard')
    return lines.join('\n')
}

export default function DealMemoView({ model, synthesis, projectName, documents }: Props) {
    const [copied, setCopied] = useState(false)
    const facts = parseDocumentedFacts(model.documentedFactsJson)
    const revenue = facts.revenue?.value
    const ebitda = facts.ebitda_sde?.value
    const price = model.askingPrice ?? model.purchasePrice
    const multiple = price && ebitda ? (price / Number(ebitda)).toFixed(1) : null

    const handleCopy = useCallback(() => {
        navigator.clipboard.writeText(buildMemoText(model, synthesis, projectName))
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
    }, [model, synthesis, projectName])

    const handlePrint = useCallback(() => {
        window.print()
    }, [])

    const conf = parseFloat(synthesis?.valuationConfidence || synthesis?.aiConfidence || '')
    const confPct = Number.isFinite(conf) ? (conf <= 1 ? Math.round(conf * 100) : Math.round(conf)) : null

    return (
        <Card className="overflow-hidden print:border-0 print:shadow-none">
            <CardHeader className="border-b border-border bg-card/80 print:border-0">
                <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                        <FileText className="h-5 w-5 text-primary" />
                        <CardTitle className="text-lg">Deal memo</CardTitle>
                    </div>
                    <div className="flex gap-2 print:hidden">
                        <Button variant="outline" size="sm" onClick={handleCopy}>
                            {copied ? <Check className="mr-1 h-3.5 w-3.5" /> : <Copy className="mr-1 h-3.5 w-3.5" />}
                            {copied ? 'Copied' : 'Copy'}
                        </Button>
                        <Button variant="outline" size="sm" onClick={handlePrint}>
                            <Printer className="mr-1 h-3.5 w-3.5" />
                            Print
                        </Button>
                    </div>
                </div>
            </CardHeader>
            <CardContent className="p-5 space-y-5">
                <div>
                    <h2 className="text-xl font-bold text-foreground">{projectName}</h2>
                    <p className="text-sm text-muted-foreground">{new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} · {documents.filter(d => d.status === 'completed').length} documents analyzed</p>
                </div>

                <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
                    <div className="rounded-lg border border-border p-3">
                        <p className="text-[11px] uppercase tracking-wide text-muted-foreground">Revenue</p>
                        <p className="mt-1 text-lg font-bold">{typeof revenue === 'number' ? money(revenue) : '—'}</p>
                    </div>
                    <div className="rounded-lg border border-border p-3">
                        <p className="text-[11px] uppercase tracking-wide text-muted-foreground">EBITDA/SDE</p>
                        <p className="mt-1 text-lg font-bold">{typeof ebitda === 'number' ? money(ebitda) : '—'}</p>
                    </div>
                    <div className="rounded-lg border border-border p-3">
                        <p className="text-[11px] uppercase tracking-wide text-muted-foreground">Price</p>
                        <p className="mt-1 text-lg font-bold">{typeof price === 'number' ? money(price) : '—'}</p>
                    </div>
                    <div className="rounded-lg border border-border p-3">
                        <p className="text-[11px] uppercase tracking-wide text-muted-foreground">Multiple</p>
                        <p className="mt-1 text-lg font-bold">{multiple ? `${multiple}x` : '—'}</p>
                    </div>
                </div>

                {synthesis ? (
                    <>
                        <div className="flex flex-wrap items-center gap-2">
                            <Badge variant={synthesis.finalTrafficLight === 'GREEN' ? 'success' : synthesis.finalTrafficLight === 'RED' ? 'destructive' : 'warning'} className="text-sm px-3 py-1">
                                {synthesis.finalRecommendation || 'Pending'}
                            </Badge>
                            <Badge variant="outline">{synthesis.finalTrafficLight || synthesis.finalRiskLevel}</Badge>
                            {confPct !== null && (
                                <Badge variant="outline" className={confPct >= 70 ? 'text-green-600' : confPct >= 40 ? 'text-amber-600' : 'text-destructive'}>
                                    {confPct}% confidence
                                </Badge>
                            )}
                        </div>

                        {(synthesis.valuationBaseEstimate && synthesis.valuationBaseEstimate !== '0') && (
                            <div className="rounded-lg border border-primary/25 bg-primary/5 p-4">
                                <p className="text-xs font-semibold uppercase tracking-wide text-primary">Valuation range</p>
                                <p className="mt-1 text-lg font-bold">{formatCurrencyValue(synthesis.valuationLowerBound, synthesis.valuationCurrency || 'USD')} – {formatCurrencyValue(synthesis.valuationBaseEstimate, synthesis.valuationCurrency || 'USD')} – {formatCurrencyValue(synthesis.valuationUpperBound, synthesis.valuationCurrency || 'USD')}</p>
                            </div>
                        )}

                        {synthesis.finalJudgmentSummary && (
                            <div>
                                <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground mb-1">Summary</p>
                                <p className="text-sm leading-6 text-foreground">{synthesis.finalJudgmentSummary}</p>
                            </div>
                        )}

                        {synthesis.redFlags.length > 0 && (
                            <div>
                                <p className="text-xs font-semibold uppercase tracking-wide text-destructive mb-2">Red flags ({synthesis.redFlags.length})</p>
                                <ul className="space-y-1">
                                    {synthesis.redFlags.map((flag, i) => (
                                        <TruncatedListItem key={i} text={flag} bulletColor="bg-destructive" />
                                    ))}
                                </ul>
                            </div>
                        )}

                        {synthesis.keyTakeaways?.length > 0 && (
                            <div>
                                <p className="text-xs font-semibold uppercase tracking-wide text-primary mb-2">Key takeaways</p>
                                <ul className="space-y-1">
                                    {synthesis.keyTakeaways.map((t, i) => (
                                        <TruncatedListItem key={i} text={t} bulletColor="bg-primary" />
                                    ))}
                                </ul>
                            </div>
                        )}

                        {synthesis.negotiationLevers?.length > 0 && (
                            <div>
                                <p className="text-xs font-semibold uppercase tracking-wide text-amber-600 dark:text-amber-400 mb-2">Negotiation levers</p>
                                <ul className="space-y-1">
                                    {synthesis.negotiationLevers.slice(0, 4).map((l, i) => (
                                        <TruncatedListItem key={i} text={l} bulletColor="bg-amber-500" />
                                    ))}
                                </ul>
                            </div>
                        )}

                        {synthesis.openQuestions?.length > 0 && (
                            <div>
                                <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground mb-2">Open questions</p>
                                <ul className="space-y-1">
                                    {synthesis.openQuestions.slice(0, 3).map((q, i) => (
                                        <TruncatedListItem key={i} text={q} bulletColor="bg-muted-foreground" />
                                    ))}
                                </ul>
                            </div>
                        )}
                    </>
                ) : (
                    <p className="text-sm text-muted-foreground">Synthesis pending — upload and process documents to generate the deal memo.</p>
                )}
            </CardContent>
        </Card>
    )
}
