import { useCallback, useState } from 'react'
import { Download, FileJson, FileText, Newspaper } from 'lucide-react'

import { Button } from '../lib/shadcn/button'
import type { DealModel, ProjectSynthesisItem } from '../hooks/backend/diligence'
import { parseDocumentedFacts } from '../utils/evidence'
import { formatCurrencyValue } from '../utils/aiSubmissionData'
import { entryMultiple } from '../utils/dealMath'
import { downloadTextFile } from '../utils/downloadFile'

type Props = {
    model: DealModel
    synthesis?: ProjectSynthesisItem
    projectName: string
}

function formatFactValue(value: unknown): string {
    if (typeof value === 'number') return `$${value.toLocaleString()}`
    if (typeof value === 'string' && value.trim().length > 0) return value
    return 'Not confirmed'
}

function firstItems(items: string[] | undefined, count: number): string[] {
    return (items ?? []).filter((item) => item.trim().length > 0).slice(0, count)
}

export function buildOnePageSnapshot(model: DealModel, synthesis: ProjectSynthesisItem | undefined, projectName: string): string {
    const facts = parseDocumentedFacts(model.documentedFactsJson)
    const lines: string[] = []
    const risk = synthesis?.finalRiskLevel || 'Pending'
    const signal = synthesis?.finalTrafficLight || 'Pending'
    const recommendation = synthesis?.finalRecommendation || 'Pending final recommendation'
    const price = model.purchasePrice || model.askingPrice
    const ebitda = typeof facts.ebitda_sde?.value === 'number' ? facts.ebitda_sde.value : null
    // Reuse the canonical multiple, which returns null for a non-positive EBITDA
    // rather than emitting a meaningless negative "x" for a loss-making target.
    const multipleValue = entryMultiple(price ?? null, ebitda)
    const entryMultipleLabel = multipleValue !== null ? `${multipleValue.toFixed(1)}x EBITDA/SDE` : 'Not available'

    lines.push(`# Deal Snapshot: ${projectName}`)
    lines.push('')
    lines.push(`*Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}*`)
    lines.push('')
    lines.push(`**Recommendation:** ${recommendation}`)
    lines.push(`**Risk / signal:** ${risk} / ${signal}`)
    lines.push(`**Entry multiple:** ${entryMultipleLabel}`)
    lines.push('')
    lines.push('## Key Numbers')
    lines.push(`- Revenue: ${formatFactValue(facts.revenue?.value)}`)
    lines.push(`- EBITDA/SDE: ${formatFactValue(facts.ebitda_sde?.value)}`)
    lines.push(`- Asking/Purchase price: ${price ? `$${price.toLocaleString()}` : 'Not set'}`)
    if (synthesis?.valuationBaseEstimate && synthesis.valuationBaseEstimate !== '0') {
        lines.push(`- Valuation range: ${formatCurrencyValue(synthesis.valuationLowerBound, synthesis.valuationCurrency || 'USD') || 'Pending'} – ${formatCurrencyValue(synthesis.valuationBaseEstimate, synthesis.valuationCurrency || 'USD') || 'Pending'} – ${formatCurrencyValue(synthesis.valuationUpperBound, synthesis.valuationCurrency || 'USD') || 'Pending'}`)
    }
    lines.push('')
    lines.push('## Top Risks')
    const risks = firstItems(synthesis?.redFlags, 3)
    lines.push(...(risks.length ? risks.map((item) => `- ${item}`) : ['- No red flags returned yet.']))
    lines.push('')
    lines.push('## Top Positives')
    const positives = firstItems(synthesis?.greenFlags, 3)
    lines.push(...(positives.length ? positives.map((item) => `- ${item}`) : ['- No green flags returned yet.']))
    lines.push('')
    lines.push('## Next Questions')
    const questions = firstItems(synthesis?.openQuestions, 3)
    lines.push(...(questions.length ? questions.map((item) => `- ${item}`) : ['- No open questions returned yet.']))
    lines.push('')
    lines.push('---')
    lines.push('*One-page snapshot generated by Dillon AI. Not financial advice.*')

    return lines.join('\n')
}

export function buildMarkdownReport(model: DealModel, synthesis: ProjectSynthesisItem | undefined, projectName: string): string {
    const facts = parseDocumentedFacts(model.documentedFactsJson)
    const lines: string[] = []

    lines.push(`# Due Diligence Summary: ${projectName}`)
    lines.push(``)
    lines.push(`*Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}*`)
    lines.push(``)

    lines.push(`## Deal Overview`)
    lines.push(``)
    if (model.askingPrice) lines.push(`- **Asking Price:** $${model.askingPrice.toLocaleString()}`)
    if (model.purchasePrice) lines.push(`- **Purchase Price:** $${model.purchasePrice.toLocaleString()}`)
    if (facts.revenue?.value) lines.push(`- **Revenue:** $${Number(facts.revenue.value).toLocaleString()}`)
    if (facts.ebitda_sde?.value) lines.push(`- **EBITDA/SDE:** $${Number(facts.ebitda_sde.value).toLocaleString()}`)
    if (facts.gross_profit?.value) lines.push(`- **Gross Profit:** $${Number(facts.gross_profit.value).toLocaleString()}`)
    const reportMultiple = entryMultiple(
        model.purchasePrice ?? null,
        typeof facts.ebitda_sde?.value === 'number' ? facts.ebitda_sde.value : null,
    )
    if (reportMultiple !== null) {
        lines.push(`- **Entry Multiple:** ${reportMultiple.toFixed(1)}x`)
    }
    lines.push(``)

    if (synthesis) {
        if ((synthesis.valuationBaseEstimate && synthesis.valuationBaseEstimate !== '0') || (synthesis.valuationLowerBound && synthesis.valuationLowerBound !== '0')) {
            lines.push(`## Valuation Range`)
            lines.push(``)
            lines.push(`- **Lower Bound:** ${formatCurrencyValue(synthesis.valuationLowerBound, synthesis.valuationCurrency || 'USD') || 'Pending'}`)
            lines.push(`- **Base Estimate:** ${formatCurrencyValue(synthesis.valuationBaseEstimate, synthesis.valuationCurrency || 'USD') || 'Pending'}`)
            lines.push(`- **Upper Bound:** ${formatCurrencyValue(synthesis.valuationUpperBound, synthesis.valuationCurrency || 'USD') || 'Pending'}`)
            const conf = parseFloat(synthesis.valuationConfidence || synthesis.aiConfidence || '')
            if (Number.isFinite(conf)) {
                const pct = conf <= 1 ? Math.round(conf * 100) : Math.round(conf)
                lines.push(`- **Confidence:** ${pct}% (${pct >= 70 ? 'High' : pct >= 40 ? 'Medium' : 'Low'})`)
            }
            lines.push(``)
        }

        lines.push(`## Risk Assessment`)
        lines.push(``)
        lines.push(`- **Overall Risk:** ${synthesis.finalRiskLevel}`)
        lines.push(`- **Traffic Light:** ${synthesis.finalTrafficLight}`)
        lines.push(``)

        if (synthesis.redFlags.length > 0) {
            lines.push(`### Red Flags`)
            synthesis.redFlags.forEach(f => lines.push(`- ${f}`))
            lines.push(``)
        }

        if (synthesis.yellowFlags?.length) {
            lines.push(`### Yellow Flags`)
            synthesis.yellowFlags.forEach(f => lines.push(`- ${f}`))
            lines.push(``)
        }

        if (synthesis.greenFlags?.length) {
            lines.push(`### Green Flags`)
            synthesis.greenFlags.forEach(f => lines.push(`- ${f}`))
            lines.push(``)
        }

        if (synthesis.openQuestions?.length) {
            lines.push(`### Open Questions`)
            synthesis.openQuestions.forEach(q => lines.push(`- ${q}`))
            lines.push(``)
        }

        if (synthesis.negotiationLevers?.length) {
            lines.push(`### Negotiation Levers`)
            synthesis.negotiationLevers.forEach(l => lines.push(`- ${l}`))
            lines.push(``)
        }

        if (synthesis.missingDocuments?.length) {
            lines.push(`### Missing Documents`)
            synthesis.missingDocuments.forEach(d => lines.push(`- ${d}`))
            lines.push(``)
        }
    }

    lines.push(`## Model Assumptions`)
    lines.push(``)
    if (model.holdPeriodYears) lines.push(`- Hold Period: ${model.holdPeriodYears} years`)
    if (model.baseRevenueGrowth) lines.push(`- Base Revenue Growth: ${(model.baseRevenueGrowth * 100).toFixed(1)}%`)
    if (model.baseEbitdaMargin) lines.push(`- Base EBITDA Margin: ${(model.baseEbitdaMargin * 100).toFixed(1)}%`)
    if (model.exitMultiple) lines.push(`- Exit Multiple: ${model.exitMultiple}x`)
    if (model.taxRate) lines.push(`- Tax Rate: ${(model.taxRate * 100).toFixed(1)}%`)
    if (model.interestRate) lines.push(`- Interest Rate: ${(model.interestRate * 100).toFixed(1)}%`)
    lines.push(``)

    lines.push(`---`)
    lines.push(`*This report was generated by Dillon AI Due Diligence Dashboard. It is not financial advice.*`)

    return lines.join('\n')
}

export function buildJsonExport(model: DealModel, synthesis: ProjectSynthesisItem | undefined, projectName: string) {
    const facts = parseDocumentedFacts(model.documentedFactsJson)
    return {
        projectName,
        exportedAt: new Date().toISOString(),
        dealModel: {
            askingPrice: model.askingPrice,
            purchasePrice: model.purchasePrice,
            holdPeriodYears: model.holdPeriodYears,
            baseRevenueGrowth: model.baseRevenueGrowth,
            baseEbitdaMargin: model.baseEbitdaMargin,
            exitMultiple: model.exitMultiple,
            interestRate: model.interestRate,
            taxRate: model.taxRate,
        },
        documentedFacts: facts,
        synthesis: synthesis ? {
            riskLevel: synthesis.finalRiskLevel,
            trafficLight: synthesis.finalTrafficLight,
            redFlags: synthesis.redFlags,
            yellowFlags: synthesis.yellowFlags,
            greenFlags: synthesis.greenFlags,
            openQuestions: synthesis.openQuestions,
            negotiationLevers: synthesis.negotiationLevers,
            missingDocuments: synthesis.missingDocuments,
        } : null,
    }
}

export function downloadFile(content: string, filename: string, mimeType: string) {
    // Delegate to the shared helper, which revokes the object URL on the next
    // tick. Revoking synchronously (as this used to) can cancel an in-flight
    // download in browsers that start the save asynchronously after click().
    downloadTextFile(filename, content, mimeType)
}

export default function ExportDealButton({ model, synthesis, projectName }: Props) {
    const [showMenu, setShowMenu] = useState(false)

    const handleSnapshot = useCallback(() => {
        const snapshot = buildOnePageSnapshot(model, synthesis, projectName)
        const safeName = projectName.replace(/[^a-zA-Z0-9-_]/g, '_').slice(0, 50) || 'deal'
        downloadFile(snapshot, `${safeName}_snapshot.md`, 'text/markdown')
        setShowMenu(false)
    }, [model, synthesis, projectName])

    const handleMarkdown = useCallback(() => {
        const md = buildMarkdownReport(model, synthesis, projectName)
        const safeName = projectName.replace(/[^a-zA-Z0-9-_]/g, '_').slice(0, 50) || 'deal'
        downloadFile(md, `${safeName}_summary.md`, 'text/markdown')
        setShowMenu(false)
    }, [model, synthesis, projectName])

    const handleJson = useCallback(() => {
        const data = buildJsonExport(model, synthesis, projectName)
        const safeName = projectName.replace(/[^a-zA-Z0-9-_]/g, '_').slice(0, 50) || 'deal'
        downloadFile(JSON.stringify(data, null, 2), `${safeName}_export.json`, 'application/json')
        setShowMenu(false)
    }, [model, synthesis, projectName])

    return (
        <div className="relative">
            <Button
                id="export-deal-btn"
                data-export-btn="true"
                type="button"
                variant="outline"
                className="gap-2 px-4 py-2 text-sm"
                onClick={() => setShowMenu(!showMenu)}
            >
                <Download className="h-4 w-4" />
                Export
            </Button>
            {showMenu && (
                <>
                    <div className="fixed inset-0 z-40" onClick={() => setShowMenu(false)} />
                    <div className="absolute right-0 top-full z-50 mt-1 w-56 rounded-md border border-border bg-popover p-1 shadow-lg">
                        <button
                            onClick={handleSnapshot}
                            className="flex w-full items-center gap-2 rounded-sm px-2 py-1.5 text-sm text-foreground hover:bg-muted"
                        >
                            <Newspaper className="h-4 w-4 text-muted-foreground" />
                            One-page snapshot
                        </button>
                        <button
                            onClick={handleMarkdown}
                            className="flex w-full items-center gap-2 rounded-sm px-2 py-1.5 text-sm text-foreground hover:bg-muted"
                        >
                            <FileText className="h-4 w-4 text-muted-foreground" />
                            Summary (Markdown)
                        </button>
                        <button
                            onClick={handleJson}
                            className="flex w-full items-center gap-2 rounded-sm px-2 py-1.5 text-sm text-foreground hover:bg-muted"
                        >
                            <FileJson className="h-4 w-4 text-muted-foreground" />
                            Raw data (JSON)
                        </button>
                    </div>
                </>
            )}
        </div>
    )
}
