import { useCallback, useState } from 'react'
import { Download, FileJson, FileText, Newspaper, FileSpreadsheet, Loader2, Printer, Scale } from 'lucide-react'

import { Button } from '../lib/shadcn/button'
import type { DealModel, ProjectSynthesisItem } from '../hooks/backend/diligence'
import { parseDocumentedFacts } from '../utils/evidence'
import { formatCurrencyValue } from '../utils/aiSubmissionData'
import { entryMultiple } from '../utils/dealMath'
import { downloadTextFile } from '../utils/downloadFile'
import { confidenceToPercent } from '../utils/diligenceDashboardUtils'
import { ExportDiligenceModal } from './ExportDiligenceModal'
import type { SubmissionHistoryItem } from '../utils/submissionHistory'

type Props = {
    model: DealModel
    synthesis?: ProjectSynthesisItem
    projectName: string
    projectId?: string
    documents?: SubmissionHistoryItem[]
    onOpenIcMemoModal?: (initialDocType?: 'ic_memo' | 'loi') => void
}

function formatFactValue(value: unknown): string {
    if (typeof value === 'number' && Number.isFinite(value)) {
        // Put the minus before the dollar sign ("-$500,000", not "$-500,000")
        // and never render a non-finite number as "$NaN".
        return value < 0 ? `-$${Math.abs(value).toLocaleString()}` : `$${value.toLocaleString()}`
    }
    if (typeof value === 'string' && value.trim().length > 0) return value
    return 'Not confirmed'
}

function firstItems(items: string[] | undefined, count: number): string[] {
    return (items ?? []).filter((item) => item.trim().length > 0).slice(0, count)
}

export function buildOnePageSnapshot(model: DealModel, synthesis: ProjectSynthesisItem | undefined, projectName: string): string {
    const facts = parseDocumentedFacts(model.documentedFactsJson)
    const lines: string[] = []
    const risk = synthesis?.finalRiskLevel || 'Pending'
    const signal = synthesis?.finalTrafficLight || 'Pending'
    const recommendation = synthesis?.finalRecommendation || 'Pending final recommendation'
    const price = model.purchasePrice || model.askingPrice
    const ebitda = typeof facts.ebitda_sde?.value === 'number' ? facts.ebitda_sde.value : null
    // Reuse the canonical multiple, which returns null for a non-positive EBITDA
    // rather than emitting a meaningless negative "x" for a loss-making target.
    const multipleValue = entryMultiple(price ?? null, ebitda)
    const entryMultipleLabel = multipleValue !== null ? `${multipleValue.toFixed(1)}x EBITDA/SDE` : 'Not available'

    lines.push(`# Deal Snapshot: ${projectName}`)
    lines.push('')
    lines.push(`*Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}*`)
    lines.push('')
    lines.push(`**Recommendation:** ${recommendation}`)
    lines.push(`**Risk / signal:** ${risk} / ${signal}`)
    lines.push(`**Entry multiple:** ${entryMultipleLabel}`)
    lines.push('')
    lines.push('## Key Numbers')
    lines.push(`- Revenue: ${formatFactValue(facts.revenue?.value)}`)
    lines.push(`- EBITDA/SDE: ${formatFactValue(facts.ebitda_sde?.value)}`)
    lines.push(`- Asking/Purchase price: ${price ? `$${price.toLocaleString()}` : 'Not set'}`)
    if (synthesis?.valuationBaseEstimate && synthesis.valuationBaseEstimate !== '0') {
        lines.push(`- Valuation range: ${formatCurrencyValue(synthesis.valuationLowerBound, synthesis.valuationCurrency || 'USD') || 'Pending'} – ${formatCurrencyValue(synthesis.valuationBaseEstimate, synthesis.valuationCurrency || 'USD') || 'Pending'} – ${formatCurrencyValue(synthesis.valuationUpperBound, synthesis.valuationCurrency || 'USD') || 'Pending'}`)
    }
    lines.push('')
    lines.push('## Top Risks')
    const risks = firstItems(synthesis?.redFlags, 3)
    lines.push(...(risks.length ? risks.map((item) => `- ${item}`) : ['- No red flags returned yet.']))
    lines.push('')
    lines.push('## Top Positives')
    const positives = firstItems(synthesis?.greenFlags, 3)
    lines.push(...(positives.length ? positives.map((item) => `- ${item}`) : ['- No green flags returned yet.']))
    lines.push('')
    lines.push('## Next Questions')
    const questions = firstItems(synthesis?.openQuestions, 3)
    lines.push(...(questions.length ? questions.map((item) => `- ${item}`) : ['- No open questions returned yet.']))
    lines.push('')
    lines.push('---')
    lines.push('*One-page snapshot generated by Dillon AI. Not financial advice.*')

    return lines.join('\n')
}

export function buildMarkdownReport(model: DealModel, synthesis: ProjectSynthesisItem | undefined, projectName: string): string {
    const facts = parseDocumentedFacts(model.documentedFactsJson)
    const lines: string[] = []

    lines.push(`# Due Diligence Summary: ${projectName}`)
    lines.push(``)
    lines.push(`*Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}*`)
    lines.push(``)

    lines.push(`## Deal Overview`)
    lines.push(``)
    if (model.askingPrice) lines.push(`- **Asking Price:** $${model.askingPrice.toLocaleString()}`)
    if (model.purchasePrice) lines.push(`- **Purchase Price:** $${model.purchasePrice.toLocaleString()}`)
    if (facts.revenue?.value) lines.push(`- **Revenue:** $${Number(facts.revenue.value).toLocaleString()}`)
    if (facts.ebitda_sde?.value) lines.push(`- **EBITDA/SDE:** $${Number(facts.ebitda_sde.value).toLocaleString()}`)
    if (facts.gross_profit?.value) lines.push(`- **Gross Profit:** $${Number(facts.gross_profit.value).toLocaleString()}`)
    const reportMultiple = entryMultiple(
        model.purchasePrice ?? null,
        typeof facts.ebitda_sde?.value === 'number' ? facts.ebitda_sde.value : null,
    )
    if (reportMultiple !== null) {
        lines.push(`- **Entry Multiple:** ${reportMultiple.toFixed(1)}x`)
    }
    lines.push(``)

    if (synthesis) {
        if ((synthesis.valuationBaseEstimate && synthesis.valuationBaseEstimate !== '0') || (synthesis.valuationLowerBound && synthesis.valuationLowerBound !== '0')) {
            lines.push(`## Valuation Range`)
            lines.push(``)
            lines.push(`- **Lower Bound:** ${formatCurrencyValue(synthesis.valuationLowerBound, synthesis.valuationCurrency || 'USD') || 'Pending'}`)
            lines.push(`- **Base Estimate:** ${formatCurrencyValue(synthesis.valuationBaseEstimate, synthesis.valuationCurrency || 'USD') || 'Pending'}`)
            lines.push(`- **Upper Bound:** ${formatCurrencyValue(synthesis.valuationUpperBound, synthesis.valuationCurrency || 'USD') || 'Pending'}`)
            const pct = confidenceToPercent(synthesis.valuationConfidence || synthesis.aiConfidence)
            if (pct !== null) {
                lines.push(`- **Confidence:** ${pct}% (${pct >= 70 ? 'High' : pct >= 40 ? 'Medium' : 'Low'})`)
            }
            lines.push(``)
        }

        lines.push(`## Risk Assessment`)
        lines.push(``)
        lines.push(`- **Overall Risk:** ${synthesis.finalRiskLevel}`)
        lines.push(`- **Traffic Light:** ${synthesis.finalTrafficLight}`)
        lines.push(``)

        if (synthesis.redFlags.length > 0) {
            lines.push(`### Red Flags`)
            synthesis.redFlags.forEach(f => lines.push(`- ${f}`))
            lines.push(``)
        }

        if (synthesis.yellowFlags?.length) {
            lines.push(`### Yellow Flags`)
            synthesis.yellowFlags.forEach(f => lines.push(`- ${f}`))
            lines.push(``)
        }

        if (synthesis.greenFlags?.length) {
            lines.push(`### Green Flags`)
            synthesis.greenFlags.forEach(f => lines.push(`- ${f}`))
            lines.push(``)
        }

        if (synthesis.openQuestions?.length) {
            lines.push(`### Open Questions`)
            synthesis.openQuestions.forEach(q => lines.push(`- ${q}`))
            lines.push(``)
        }

        if (synthesis.negotiationLevers?.length) {
            lines.push(`### Negotiation Levers`)
            synthesis.negotiationLevers.forEach(l => lines.push(`- ${l}`))
            lines.push(``)
        }

        if (synthesis.missingDocuments?.length) {
            lines.push(`### Missing Documents`)
            synthesis.missingDocuments.forEach(d => lines.push(`- ${d}`))
            lines.push(``)
        }
    }

    lines.push(`## Model Assumptions`)
    lines.push(``)
    if (model.holdPeriodYears) lines.push(`- Hold Period: ${model.holdPeriodYears} years`)
    if (model.baseRevenueGrowth) lines.push(`- Base Revenue Growth: ${(model.baseRevenueGrowth * 100).toFixed(1)}%`)
    if (model.baseEbitdaMargin) lines.push(`- Base EBITDA Margin: ${(model.baseEbitdaMargin * 100).toFixed(1)}%`)
    if (model.exitMultiple) lines.push(`- Exit Multiple: ${model.exitMultiple}x`)
    if (model.taxRate) lines.push(`- Tax Rate: ${(model.taxRate * 100).toFixed(1)}%`)
    if (model.interestRate) lines.push(`- Interest Rate: ${(model.interestRate * 100).toFixed(1)}%`)
    lines.push(``)

    lines.push(`---`)
    lines.push(`*This report was generated by Dillon AI Due Diligence Dashboard. It is not financial advice.*`)

    return lines.join('\n')
}

export function buildJsonExport(model: DealModel, synthesis: ProjectSynthesisItem | undefined, projectName: string) {
    const facts = parseDocumentedFacts(model.documentedFactsJson)
    return {
        projectName,
        exportedAt: new Date().toISOString(),
        dealModel: {
            askingPrice: model.askingPrice,
            purchasePrice: model.purchasePrice,
            holdPeriodYears: model.holdPeriodYears,
            baseRevenueGrowth: model.baseRevenueGrowth,
            baseEbitdaMargin: model.baseEbitdaMargin,
            exitMultiple: model.exitMultiple,
            interestRate: model.interestRate,
            taxRate: model.taxRate,
        },
        documentedFacts: facts,
        synthesis: synthesis ? {
            riskLevel: synthesis.finalRiskLevel,
            trafficLight: synthesis.finalTrafficLight,
            redFlags: synthesis.redFlags,
            yellowFlags: synthesis.yellowFlags,
            greenFlags: synthesis.greenFlags,
            openQuestions: synthesis.openQuestions,
            negotiationLevers: synthesis.negotiationLevers,
            missingDocuments: synthesis.missingDocuments,
        } : null,
    }
}

export function downloadFile(content: string, filename: string, mimeType: string) {
    // Delegate to the shared helper, which revokes the object URL on the next
    // tick. Revoking synchronously (as this used to) can cancel an in-flight
    // download in browsers that start the save asynchronously after click().
    downloadTextFile(filename, content, mimeType)
}

export default function ExportDealButton({
    model,
    synthesis,
    projectName,
    projectId,
    documents,
    onOpenIcMemoModal,
}: Props) {
    const [showMenu, setShowMenu] = useState(false)
    const [isIcModalOpen, setIsIcModalOpen] = useState(false)
    const [selectedDocType, setSelectedDocType] = useState<'ic_memo' | 'loi'>('ic_memo')

    const handleSnapshot = useCallback(() => {
        const snapshot = buildOnePageSnapshot(model, synthesis, projectName)
        const safeName = projectName.replace(/[^a-zA-Z0-9-_]/g, '_').slice(0, 50) || 'deal'
        downloadFile(snapshot, `${safeName}_snapshot.md`, 'text/markdown')
        setShowMenu(false)
    }, [model, synthesis, projectName])

    const handleMarkdown = useCallback(() => {
        const md = buildMarkdownReport(model, synthesis, projectName)
        const safeName = projectName.replace(/[^a-zA-Z0-9-_]/g, '_').slice(0, 50) || 'deal'
        downloadFile(md, `${safeName}_summary.md`, 'text/markdown')
        setShowMenu(false)
    }, [model, synthesis, projectName])

    const handleJson = useCallback(() => {
        const data = buildJsonExport(model, synthesis, projectName)
        const safeName = projectName.replace(/[^a-zA-Z0-9-_]/g, '_').slice(0, 50) || 'deal'
        downloadFile(JSON.stringify(data, null, 2), `${safeName}_export.json`, 'application/json')
        setShowMenu(false)
    }, [model, synthesis, projectName])

    const [isExportingExcel, setIsExportingExcel] = useState(false)

    const handleExcel = useCallback(async () => {
        setIsExportingExcel(true)
        try {
            const { generateLiveExcelModel } = await import('../utils/excelModelGenerator')
            const blob = await generateLiveExcelModel({ model, synthesis, projectName })
            const safeName = projectName.replace(/[^a-zA-Z0-9-_]/g, '_').slice(0, 50) || 'deal'
            const url = URL.createObjectURL(blob)
            const a = document.createElement('a')
            a.href = url
            a.download = `${safeName}_financial_model.xlsx`
            document.body.appendChild(a)
            a.click()
            document.body.removeChild(a)
            setTimeout(() => URL.revokeObjectURL(url), 1000)
        } catch (err) {
            console.error('Failed to export Excel model:', err)
        } finally {
            setIsExportingExcel(false)
            setShowMenu(false)
        }
    }, [model, synthesis, projectName])

    return (
        <div className="relative">
            <Button
                id="export-deal-btn"
                data-export-btn="true"
                type="button"
                variant="outline"
                className="gap-2 px-4 py-2 text-sm"
                onClick={() => setShowMenu(!showMenu)}
            >
                {isExportingExcel ? (
                    <Loader2 className="h-4 w-4 animate-spin text-primary" />
                ) : (
                    <Download className="h-4 w-4" />
                )}
                Export
            </Button>
            {showMenu && (
                <>
                    <div className="fixed inset-0 z-[90]" onClick={() => setShowMenu(false)} />
                    <div className="absolute right-0 top-full z-[100] mt-1.5 w-80 rounded-lg border border-border bg-popover p-1.5 shadow-2xl animate-in fade-in-0 zoom-in-95 duration-150">
                        <div className="px-2 py-1 mb-1 border-b border-border/50">
                            <p className="text-[11px] font-semibold text-muted-foreground uppercase tracking-wider">Export Deal Package</p>
                        </div>
                        <button
                            id="export-ic-memo-btn"
                            onClick={() => {
                                setShowMenu(false)
                                setSelectedDocType('ic_memo')
                                if (onOpenIcMemoModal) {
                                    onOpenIcMemoModal('ic_memo')
                                } else {
                                    setIsIcModalOpen(true)
                                }
                            }}
                            className="flex w-full items-start gap-3 rounded-md p-2 text-sm font-medium text-foreground hover:bg-muted/80 transition-colors"
                        >
                            <div className="mt-0.5 rounded p-1 bg-primary/10 text-primary">
                                <Printer className="h-4 w-4" />
                            </div>
                            <div className="text-left flex-1">
                                <p className="font-semibold text-xs flex items-center gap-1.5">
                                    IC Deal Memo (.pdf / Print)
                                    <span className="text-[9px] px-1.5 py-0.5 rounded bg-primary/15 text-primary font-bold">New</span>
                                </p>
                                <p className="text-[11px] text-muted-foreground">Publication-grade letter memo with QoE bridge &amp; APA covenants</p>
                            </div>
                        </button>
                        <button
                            id="export-loi-btn"
                            onClick={() => {
                                setShowMenu(false)
                                setSelectedDocType('loi')
                                if (onOpenIcMemoModal) {
                                    onOpenIcMemoModal('loi')
                                } else {
                                    setIsIcModalOpen(true)
                                }
                            }}
                            className="flex w-full items-start gap-3 rounded-md p-2 text-sm font-medium text-foreground hover:bg-muted/80 transition-colors"
                        >
                            <div className="mt-0.5 rounded p-1 bg-violet-500/10 text-violet-600 dark:text-violet-400">
                                <Scale className="h-4 w-4" />
                            </div>
                            <div className="text-left flex-1">
                                <p className="font-semibold text-xs flex items-center gap-1.5">
                                    Letter of Intent (LOI)
                                    <span className="text-[9px] px-1.5 py-0.5 rounded bg-violet-500/15 text-violet-600 dark:text-violet-400 font-bold">New</span>
                                </p>
                                <p className="text-[11px] text-muted-foreground">Formal acquisition proposal with capital stack, peg &amp; escrow</p>
                            </div>
                        </button>
                        <button
                            onClick={handleExcel}
                            disabled={isExportingExcel}
                            className="flex w-full items-start gap-3 rounded-md p-2 text-sm font-medium text-foreground hover:bg-muted/80 transition-colors"
                        >
                            <div className="mt-0.5 rounded p-1 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">
                                <FileSpreadsheet className="h-4 w-4" />
                            </div>
                            <div className="text-left flex-1">
                                <p className="font-semibold text-xs">Live Excel Model (.xlsx)</p>
                                <p className="text-[11px] text-muted-foreground">3-Statement, Debt Amortization & IRR formulas</p>
                            </div>
                        </button>
                        <button
                            onClick={handleSnapshot}
                            className="flex w-full items-start gap-3 rounded-md p-2 text-sm text-foreground hover:bg-muted/80 transition-colors"
                        >
                            <div className="mt-0.5 rounded p-1 bg-blue-500/10 text-blue-600 dark:text-blue-400">
                                <Newspaper className="h-4 w-4" />
                            </div>
                            <div className="text-left flex-1">
                                <p className="font-semibold text-xs">One-Page Snapshot (.md)</p>
                                <p className="text-[11px] text-muted-foreground">Clean executive deal brief for quick review</p>
                            </div>
                        </button>
                        <button
                            onClick={handleMarkdown}
                            className="flex w-full items-start gap-3 rounded-md p-2 text-sm text-foreground hover:bg-muted/80 transition-colors"
                        >
                            <div className="mt-0.5 rounded p-1 bg-purple-500/10 text-purple-600 dark:text-purple-400">
                                <FileText className="h-4 w-4" />
                            </div>
                            <div className="text-left flex-1">
                                <p className="font-semibold text-xs">Full Diligence Memo (.md)</p>
                                <p className="text-[11px] text-muted-foreground">Complete findings, red flags & valuation</p>
                            </div>
                        </button>
                        <button
                            onClick={handleJson}
                            className="flex w-full items-start gap-3 rounded-md p-2 text-sm text-foreground hover:bg-muted/80 transition-colors"
                        >
                            <div className="mt-0.5 rounded p-1 bg-amber-500/10 text-amber-600 dark:text-amber-400">
                                <FileJson className="h-4 w-4" />
                            </div>
                            <div className="text-left flex-1">
                                <p className="font-semibold text-xs">Raw Deal Data (.json)</p>
                                <p className="text-[11px] text-muted-foreground">Machine-readable model facts & synthesis</p>
                            </div>
                        </button>
                    </div>
                </>
            )}
            <ExportDiligenceModal
                open={isIcModalOpen}
                onOpenChange={setIsIcModalOpen}
                dealName={projectName}
                projectId={projectId || 'PROJ-MAIN'}
                synthesis={synthesis}
                dealModel={model}
                documents={documents}
                initialDocumentType={selectedDocType}
            />
        </div>
    )
}
