import { Landmark } from 'lucide-react'

import type { DealModel } from '../hooks/backend/diligence'
import { Badge } from '../lib/shadcn/badge'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../lib/shadcn/card'

function getEbitda(model: DealModel) {
    try { const fact = JSON.parse(model.documentedFactsJson || '{}').ebitda_sde; return fact?.status === 'confirmed' && typeof fact.value === 'number' ? fact.value : null } catch { return null }
}
function money(value: number) { return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value) }
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-lg border border-border bg-background p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-lg font-semibold text-foreground">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div> }

export default function FinancedReturnsCard({ model }: { model: DealModel }) {
    const ebitda = getEbitda(model); const price = model.purchasePrice ?? model.askingPrice; const tax = model.taxRate; const equityPct = model.equityContributionPercent; const rate = model.interestRate; const years = model.amortizationYears; const capex = model.maintenanceCapex ?? 0; const fees = model.transactionFees ?? 0; const wc = model.workingCapitalRequirement ?? 0; const sellerNote = model.sellerNoteAmount ?? 0
    const uses = price === null ? null : price + fees + wc; const debt = uses === null || equityPct === null ? null : Math.max(0, uses * (1 - equityPct) - sellerNote); const equity = uses === null || debt === null ? null : uses - debt - sellerNote; const operatingCashFlow = ebitda === null || tax === null ? null : ebitda * (1 - tax) - capex; const annualDebtService = debt === null || rate === null || years === null || years <= 0 ? null : rate === 0 ? debt / years : debt * ((rate * (1 + rate) ** years) / (((1 + rate) ** years) - 1)); const cashAfterDebt = operatingCashFlow === null || annualDebtService === null ? null : operatingCashFlow - annualDebtService; const coc = equity && cashAfterDebt !== null && equity > 0 ? cashAfterDebt / equity : null; const dscr = annualDebtService && operatingCashFlow !== null && annualDebtService > 0 ? operatingCashFlow / annualDebtService : null; const ready = cashAfterDebt !== null && equity !== null
    return <Card className="overflow-hidden border-primary/30"><CardHeader className="border-b border-primary/20 bg-primary/5"><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div><div className="flex items-center gap-2"><Landmark className="h-5 w-5 text-primary" /><CardTitle className="text-xl">Financed acquisition scenario</CardTitle></div><CardDescription className="mt-1">Level-payment debt model using saved financing assumptions.</CardDescription></div><Badge variant={ready ? 'success' : 'secondary'}>{ready ? 'Inputs available' : 'Inputs needed'}</Badge></div></CardHeader><CardContent className="space-y-4 p-5">{!ready ? <div className="rounded-lg border border-dashed border-border bg-muted/20 p-4 text-sm text-muted-foreground">Add documented EBITDA/SDE, price, tax rate, equity contribution, interest rate, and amortization term.</div> : <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Equity at close" value={money(equity!)} detail="uses − debt − seller note" /><Metric label="Annual debt service" value={money(annualDebtService!)} detail="amortizing loan payment" /><Metric label="Cash after debt service" value={money(cashAfterDebt!)} detail="operating cash flow − debt service" /><Metric label="Cash-on-cash return" value={coc === null ? 'Not available' : `${(coc * 100).toFixed(1)}%`} detail="cash after debt ÷ equity" /><Metric label="Debt-service coverage" value={dscr === null ? 'Not available' : `${dscr.toFixed(2)}x`} detail="operating cash flow ÷ debt service" /></div>}{dscr !== null && dscr < 1.25 ? <p className="rounded-md border border-warning/30 bg-warning/10 p-3 text-sm text-foreground">Downside warning: DSCR is below 1.25x. Review leverage, operating assumptions, or debt terms.</p> : null}</CardContent></Card>
}
