import { ChartNoAxesCombined } from 'lucide-react'
import type { DealModel } from '../hooks/backend/diligence'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../lib/shadcn/card'

function facts(model: DealModel) { try { return JSON.parse(model.documentedFactsJson || '{}') as Record<string, { value?: number; status?: string; currency?: string }> } catch { return {} } }
function money(value: number, currency: string) { return new Intl.NumberFormat('en-US', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value) }
export default function ScenarioComparisonCard({ model }: { model: DealModel }) {
 const documented=facts(model); const revenue=documented.revenue?.status==='confirmed'?documented.revenue.value:null; const ebitda=documented.ebitda_sde?.status==='confirmed'?documented.ebitda_sde.value:null; const currency=documented.revenue?.currency||documented.ebitda_sde?.currency||'USD'; const years=model.holdPeriodYears??5; const initial=model.purchasePrice??model.askingPrice;
 const scenarios=[['Bear',model.bearRevenueGrowth,model.bearEbitdaMargin,model.bearExitMultiple],['Base',model.baseRevenueGrowth,model.baseEbitdaMargin,model.baseExitMultiple],['Bull',model.bullRevenueGrowth,model.bullEbitdaMargin,model.bullExitMultiple]] as const;
 const ready=revenue!==null&&scenarios.every(([,g,m,x])=>g!==null&&m!==null&&x!==null);
 return <Card className="overflow-hidden"><CardHeader className="border-b border-border bg-card/80"><div className="flex items-center gap-2"><ChartNoAxesCombined className="h-5 w-5 text-primary"/><CardTitle className="text-xl">Bear / base / bull scenarios</CardTitle></div><CardDescription>Five-year projection from documented starting revenue and analyst-entered scenario assumptions.</CardDescription></CardHeader><CardContent className="p-5">{!ready?<p className="rounded-lg border border-dashed border-border bg-muted/20 p-4 text-sm text-muted-foreground">Add documented revenue plus revenue-growth, EBITDA-margin, and exit-multiple assumptions for each scenario.</p>:<div className="grid gap-3 lg:grid-cols-3">{scenarios.map(([name,growth,margin,multiple])=>{const exitRevenue=revenue!*(1+growth!)**years;const exitEbitda=exitRevenue*margin!;const exitValue=exitEbitda*multiple!;const moic=initial&&initial>0?exitValue/initial:null;return <div key={name} className="rounded-lg border border-border bg-background p-4"><p className="font-semibold">{name}</p><p className="mt-2 text-sm text-muted-foreground">Year {years} revenue</p><p className="font-medium">{money(exitRevenue,currency)}</p><p className="mt-2 text-sm text-muted-foreground">Exit EBITDA / value</p><p className="font-medium">{money(exitEbitda,currency)} / {money(exitValue,currency)}</p><p className="mt-2 text-sm text-muted-foreground">Exit-value MOIC</p><p className="font-medium">{moic===null?'Add purchase price':`${moic.toFixed(2)}x`}</p></div>})}</div>}<p className="mt-4 text-xs text-muted-foreground">Scenario assumptions are not document facts. Exit-value MOIC excludes interim cash flows and financing; IRR follows once exit cash-flow modeling is added.</p></CardContent></Card>
}
