import { AlertTriangle, RefreshCw } from 'lucide-react'
import type { WorkflowErrorItem } from '../../backend/diligence/getWorkflowErrors'
import { Badge } from '../lib/shadcn/badge'
import { Button } from '../lib/shadcn/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../lib/shadcn/card'
import { formatEasternTime } from '../utils/dateTime'

type Props = { rows: WorkflowErrorItem[]; loading: boolean; error: string | null; onRefresh: () => void }
export default function WorkflowErrorLogCard({ rows, loading, error, onRefresh }: Props) {
  return <Card className="overflow-hidden"><CardHeader className="border-b border-border bg-card/80"><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2 text-xl"><AlertTriangle className="h-5 w-5 text-warning" />Workflow reliability</CardTitle><CardDescription className="mt-1">Uncaught production failures recorded after automated retries and recovery paths are exhausted.</CardDescription></div><Button type="button" size="sm" variant="outline" disabled={loading} onClick={onRefresh}><RefreshCw className={loading ? 'animate-spin' : ''} />Refresh errors</Button></div></CardHeader><CardContent className="p-4">{error ? <div className="rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">Unable to load error audit records: {error}</div> : null}{!error && rows.length === 0 ? <div className="rounded-lg border border-success/30 bg-success/5 p-4 text-sm text-foreground">No uncaught production errors have been recorded. Automated retries and recovery paths are operating normally.</div> : null}{rows.length > 0 ? <div className="space-y-3">{rows.map((row, index) => <details key={`${row.id ?? index}-${row.occurredAt}`} className="rounded-lg border border-warning/25 bg-warning/5 p-3"><summary className="cursor-pointer list-none"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-medium text-foreground">{row.workflowName || 'Unnamed workflow'}</p><p className="mt-1 text-xs text-muted-foreground">{formatEasternTime(row.occurredAt)} · Node: {row.failedNode || row.lastNodeExecuted || 'Not recorded'}</p></div><Badge variant="destructive">{row.severity || 'uncaught'}</Badge></div><p className="mt-2 line-clamp-2 text-sm text-muted-foreground">{row.errorMessage || 'No error message recorded.'}</p></summary><div className="mt-3 border-t border-warning/20 pt-3 text-xs text-muted-foreground"><p className="whitespace-pre-wrap break-words">{row.errorMessage || 'No error message recorded.'}</p><p className="mt-2 font-mono">Workflow: {row.workflowId || '—'} · Execution: {row.executionId || '—'}</p></div></details>)}</div> : null}</CardContent></Card>
}
