import type { WorkspaceTab } from '../DealWorkspaceNav'

export interface TabMetadata {
    id: WorkspaceTab
    label: string
    category: string
    badge: string
    whatItIsFor: string
    keyDeliverables: string[]
    recommendedRole: string
    tourStepCount: number
    suggestedFocus: string
}

export const TAB_METADATA: Record<WorkspaceTab, TabMetadata> = {
    overview: {
        id: 'overview',
        label: 'Overview',
        category: 'Executive Summary',
        badge: 'IC Summary',
        whatItIsFor: 'Executive dashboard providing an instant, high-level summary of deal health, valuation multiples, critical action items, and project milestones.',
        keyDeliverables: [
            'Deal on a Page (DOAP) executive summary card',
            'Deal Health Scorecard (0–100 composite index)',
            'Acquisition timeline from LOI to closing',
            'Immediate red flag callouts & recommended actions',
        ],
        recommendedRole: 'Private Equity Partners & Investment Committees',
        tourStepCount: 4,
        suggestedFocus: 'High-level deal gating and executive go/no-go decisions',
    },
    analysis: {
        id: 'analysis',
        label: 'Analysis',
        category: 'Financial Diligence',
        badge: 'QoE & Modeling',
        whatItIsFor: 'Comprehensive Quality of Earnings (QoE) workspace reconstructing EBITDA, stress-testing breakeven revenue, auditing add-backs, and analyzing customer concentration.',
        keyDeliverables: [
            'Adjusted EBITDA reconstruction waterfall & QoE bridges',
            'Top 5 customer concentration and churn risk matrix',
            'Breakeven analysis and fixed cost operating leverage',
            'SMB industry benchmark comparison across peer SIC codes',
        ],
        recommendedRole: 'Financial Analysts, CPAs & M&A Associates',
        tourStepCount: 5,
        suggestedFocus: 'Auditing seller add-backs and verifying sustainable cash flow',
    },
    diagnostics: {
        id: 'diagnostics',
        label: 'Risk & Playbook',
        category: 'Risk Management',
        badge: 'Deal Killers',
        whatItIsFor: 'Risk assessment engine screening for deal-killer vulnerabilities, owner dependency, key person risks, and structuring the Phase II diligence request list.',
        keyDeliverables: [
            'Interactive Risk Heatmap (Financial, Legal, Operational, Regulatory)',
            'Owner dependency score and key-person succession analysis',
            'Phase II Diligence Request List (DD Tracker)',
            'Seller Diligence Q&A and management interview scripts',
        ],
        recommendedRole: 'Deal Principals, Risk Officers & Due Diligence Leads',
        tourStepCount: 4,
        suggestedFocus: 'Uncovering latent legal/operational risks before signing definitive agreements',
    },
    diligence: {
        id: 'diligence',
        label: 'Diligence',
        category: 'Data Room & OCR',
        badge: 'Intake Pipeline',
        whatItIsFor: 'Document intake and processing pipeline where CIMs, 2-year P&Ls, tax returns, and LOIs are ingested, OCR-parsed, and fact-verified with zero data hallucination.',
        keyDeliverables: [
            'Multi-document batch drag-and-drop intake vault',
            'Deterministic table isolation and line-item extraction facts',
            'Data quality reconciliation and tax-to-book variance audit',
            '1-click trigger for Pod 1 multi-document synthesis pass',
        ],
        recommendedRole: 'Deal Leads, Data Room Admins & Underwriters',
        tourStepCount: 4,
        suggestedFocus: 'Verifying ground-truth citations and triggering AI synthesis',
    },
    synthesis: {
        id: 'synthesis',
        label: 'Synthesis',
        category: 'Investment Committee',
        badge: 'AI Cross-Doc Pass',
        whatItIsFor: 'Multi-document AI reconciliation pass that cross-references all uploaded deal files to generate an authoritative acquisition verdict, traffic light, and negotiation levers.',
        keyDeliverables: [
            'Institutional Acquisition Judgment (PROCEED / RE-TRADE / PASS)',
            'Categorized Red, Yellow, and Green flag matrix',
            'Cross-document conflict detector (P&L vs Tax Return vs CIM)',
            'Negotiation concessions and price re-trade leverage points',
        ],
        recommendedRole: 'Managing Directors & Investment Committees',
        tourStepCount: 4,
        suggestedFocus: 'Cross-document reconciliation and final IC acquisition verdict',
    },
    spending: {
        id: 'spending',
        label: 'Spending & Billing',
        category: 'Operations',
        badge: 'Token Ledger',
        whatItIsFor: 'Real-time billing transparency hub tracking API tokens, OCR compute usage, LLM provider costs, and cloud execution metrics per project.',
        keyDeliverables: [
            'Cost-per-run breakdown for document extraction and synthesis',
            'Token consumption analysis across Claude and OpenAI models',
            'Projected budget forecast for full portfolio diligence',
        ],
        recommendedRole: 'Operations Managers & Managing Partners',
        tourStepCount: 3,
        suggestedFocus: 'Monitoring cloud processing unit economics',
    },
    compare: {
        id: 'compare',
        label: 'Compare Deals',
        category: 'Portfolio Strategy',
        badge: 'Pipeline Matrix',
        whatItIsFor: 'Cross-deal portfolio matrix comparing valuation multiples, EBITDA margins, risk scores, and expected IRRs across all active acquisition targets.',
        keyDeliverables: [
            'Side-by-side deal comparison table with sorting and filtering',
            'Relative valuation multiple charts across industry sectors',
            'Pipeline ranking by risk-adjusted return potential',
        ],
        recommendedRole: 'PE Portfolio Managers & Search Fund Sponsors',
        tourStepCount: 3,
        suggestedFocus: 'Allocating capital to highest-conviction deals in pipeline',
    },
    valuation: {
        id: 'valuation',
        label: 'Valuation',
        category: 'Valuation Modeling',
        badge: 'DCF & Comps',
        whatItIsFor: 'Triangulated business valuation model synthesizing Discounted Cash Flow (DCF), Precedent M&A Transactions, and EBITDA Multiple Explorer.',
        keyDeliverables: [
            '5-year DCF model with customizable WACC and terminal growth rates',
            'Precedent transactions multiple database (Bear / Base / Bull)',
            'Seller asking multiple disconnect matrix & price re-trade delta',
        ],
        recommendedRole: 'Valuation Specialists & Investment Bankers',
        tourStepCount: 4,
        suggestedFocus: 'Determining defensible purchase price range for LOI drafting',
    },
    returns: {
        id: 'returns',
        label: 'Returns',
        category: 'Returns & Waterfall',
        badge: 'IRR & MOIC',
        whatItIsFor: 'Investor returns simulator modeling 5-year levered equity waterfall, annual dividend yields, Multiple on Invested Capital (MOIC), and exit sensitivities.',
        keyDeliverables: [
            'Levered Internal Rate of Return (IRR) and MOIC projection waterfall',
            'Exit multiple sensitivity matrix (3.0x to 6.0x exit multiples)',
            '5-year investor cash flow forecast with debt paydown',
        ],
        recommendedRole: 'Equity Investors, LPs & Fund Sponsors',
        tourStepCount: 4,
        suggestedFocus: 'Validating fund hurdle rates (target IRR ≥ 25%)',
    },
    growth: {
        id: 'growth',
        label: 'Growth',
        category: 'Financial Modeling',
        badge: 'Projections',
        whatItIsFor: 'Forward-looking financial projection builder modeling organic revenue growth, pricing power expansion, customer churn, and capex requirements.',
        keyDeliverables: [
            '5-year pro forma revenue and EBITDA projections',
            'Scenario Builder (Conservative, Base Case, Aggressive Expansion)',
            'Operating leverage and customer retention sensitivity curves',
        ],
        recommendedRole: 'Operating Partners & Financial Modelers',
        tourStepCount: 3,
        suggestedFocus: 'Testing thesis durability under downside economic scenarios',
    },
    structure: {
        id: 'structure',
        label: 'Deal Structure',
        category: 'Capital Structure',
        badge: 'Sources & Uses',
        whatItIsFor: 'Capital structure and debt sizing engine modeling Sources & Uses of funds, Senior SBA 7(a) amortization schedules, and DSCR safety covenants.',
        keyDeliverables: [
            'Institutional Sources & Uses of Funds balancing table',
            '10-year monthly debt amortization schedule with principal & interest',
            'Debt Service Coverage Ratio (DSCR) stress test under interest rate spikes',
            'Seller note subordination and standby agreements',
        ],
        recommendedRole: 'SBA Lenders, Commercial Credit Officers & Deal Structurers',
        tourStepCount: 4,
        suggestedFocus: 'Verifying bank debt covenant compliance (DSCR ≥ 1.35x)',
    },
    negotiation: {
        id: 'negotiation',
        label: 'Negotiation',
        category: 'Deal Strategy',
        badge: 'Playbook',
        whatItIsFor: 'Strategic negotiation hub converting identified diligence red flags into contractual terms: indemnity escrow holdbacks, seller notes, and broker pushback scripts.',
        keyDeliverables: [
            'Data-driven price impact bridge for re-trading LOIs',
            'Negotiation playbook with customized seller and broker scripts',
            'Recommended escrow holdback and earnout milestones',
        ],
        recommendedRole: 'Lead Negotiators, Deal Brokers & Corporate Development',
        tourStepCount: 3,
        suggestedFocus: 'Arming deal leads with mathematical leverage for price concessions',
    },
    documents: {
        id: 'documents',
        label: 'Projects',
        category: 'Data Room',
        badge: 'Portfolio Vault',
        whatItIsFor: 'Project portfolio and document repository managing multi-company workspaces, VDR files, OCR extractions, and cloud sync history.',
        keyDeliverables: [
            'Active project portfolio drawer and quick project switcher',
            'Document catalog with extraction timestamps and file sizes',
            'OCR confidence inspection and raw text extraction viewer',
        ],
        recommendedRole: 'Data Room Managers & Diligence Coordinators',
        tourStepCount: 3,
        suggestedFocus: 'Organizing and switching between active pipeline projects',
    },
    shortcuts: {
        id: 'shortcuts',
        label: 'Shortcuts',
        category: 'Productivity',
        badge: 'Hotkeys',
        whatItIsFor: 'Comprehensive keyboard shortcuts matrix and interactive key simulator designed for power users and rapid M&A deal review.',
        keyDeliverables: [
            'Categorized keyboard hotkeys (Navigation, Dillon AI, Modeling, Tours)',
            'Interactive Live Keyboard Simulator with real-time keypress lighting',
            'Printable / downloadable quick-reference hotkey cheatsheet',
        ],
        recommendedRole: 'Power Users, Associates & Deal Leads',
        tourStepCount: 3,
        suggestedFocus: 'Mastering rapid deal review with zero mouse friction',
    },
    evals: {
        id: 'evals',
        label: 'Evals & Harness',
        category: 'AI Quality',
        badge: 'Model Benchmark',
        whatItIsFor: 'Platform evaluation harness displaying empirical accuracy, table extraction precision, and latency benchmarks across production LLMs.',
        keyDeliverables: [
            'Model benchmark comparison (OpenAI Terra, OpenAI Sol, etc.)',
            'Extraction accuracy scorecards across 500+ financial ground-truth items',
            'Real-time latency and throughput metrics',
        ],
        recommendedRole: 'AI Engineers, Compliance Officers & Quantitative Leads',
        tourStepCount: 3,
        suggestedFocus: 'Verifying zero-hallucination extraction accuracy',
    },
    faqs: {
        id: 'faqs',
        label: 'FAQs & Guide',
        category: 'Documentation',
        badge: 'Knowledge Base',
        whatItIsFor: 'Institutional knowledge base and methodology guide explaining financial formulas, Quality of Earnings rules, and platform capabilities.',
        keyDeliverables: [
            'Searchable M&A and financial due diligence knowledge base',
            'SBA 7(a) loan guidelines and debt sizing rules of thumb',
            'Step-by-step Quality of Earnings methodology documentation',
        ],
        recommendedRole: 'All Users & First-Time Diligence Analysts',
        tourStepCount: 3,
        suggestedFocus: 'Clarifying accounting definitions and underwriting methodologies',
    },
    history: {
        id: 'history',
        label: 'Audit Trail',
        category: 'Governance',
        badge: 'Version Ledger',
        whatItIsFor: 'Immutable version control ledger documenting every deal edit, new document ingestion, synthesis run, and financial model snapshot.',
        keyDeliverables: [
            'Chronological submission and extraction audit log',
            'Snapshot version comparison with historical delta tracking',
            'User attribution and timestamped diligence changes',
        ],
        recommendedRole: 'Compliance Officers, Auditors & Deal Partners',
        tourStepCount: 3,
        suggestedFocus: 'Reviewing audit trail for lender and LP transparency',
    },
    email: {
        id: 'email',
        label: 'Email Drafts',
        category: 'Communication',
        badge: 'Broker Outreach',
        whatItIsFor: 'Automated deal communication center generating customized broker inquiry emails, LOI submission drafts, and Phase II question packets.',
        keyDeliverables: [
            'Pre-formatted broker inquiry templates with dynamic deal facts',
            'Phase II management interview question lists',
            'Sent email logs and follow-up tracking',
        ],
        recommendedRole: 'Associates & Corporate Development Leads',
        tourStepCount: 3,
        suggestedFocus: 'Streamlining seller and broker correspondence',
    },
    errors: {
        id: 'errors',
        label: 'Errors',
        category: 'Diagnostics',
        badge: 'Pipeline Health',
        whatItIsFor: 'System error log and diagnostic console tracking OCR failures, webhook timeouts, and table parsing anomalies.',
        keyDeliverables: [
            'Real-time webhook error log from n8n workflows',
            'Failed document parsing analysis with retry triggers',
            'System health status across Supabase and AI provider APIs',
        ],
        recommendedRole: 'System Administrators & Technical Diligence Leads',
        tourStepCount: 2,
        suggestedFocus: 'Troubleshooting failed extractions or webhook errors',
    },
}
