import type { TourPlaylist, WalkthroughStep } from './walkthroughTypes'

export const CORE_FAST_STEPS: WalkthroughStep[] = [
    {
        id: 'core-step-1',
        num: 1,
        title: 'Multi-Document Deal Room Ingestion & Packet Staging',
        tab: 'diligence',
        targetElementId: 'project-intake',
        targetSelector: '[data-project-intake], #project-intake',
        tag: 'Step 1 • Deal Room Ingestion',
        badge: 'Demo Packet Staged',
        narrative: 'Upload 3-year P&Ls, tax returns, balance sheets, and signed LOIs in one batch. Dillon AI has staged a sample 4-document deal room packet for Apex Industrial Technologies with metadata and asking price.',
        proTip: 'Drag and drop multiple PDFs, Excel sheets, and Word docs simultaneously into the intake vault.',
        keyTakeaway: 'Deterministic multi-file parser supporting parallel PDF, Excel, and Word uploads.',
        simulatedAction: {
            type: 'stage_packet',
        },
        cursorPlacement: 'center',
        durationMs: 12000,
    },
    {
        id: 'core-step-2',
        num: 2,
        title: 'Parallel Batch Processing & Real-Time Ingestion Queue',
        tab: 'diligence',
        targetElementId: 'diligence-batch',
        targetSelector: '#diligence-batch, [data-batch-progress]',
        tag: 'Step 2 • Batch Processing',
        badge: '4 Parallel Workers',
        narrative: 'Clicking "Queue" initiates parallel multi-model extraction (powered by OpenAI 5.6 Terra). The agent extracts line items, performs OCR on scanned PDFs, and maps balance sheets simultaneously with live elapsed timers.',
        proTip: 'Each document runs through isolated cloud workers with automated retries and zero memory crossover.',
        keyTakeaway: 'High-throughput parallel OCR extraction with real-time status telemetry.',
        simulatedAction: {
            type: 'simulate_queue',
        },
        cursorPlacement: 'top-left',
        durationMs: 13000,
    },
    {
        id: 'core-step-3',
        num: 3,
        title: 'Extraction Fact Sheets & Ground Truth Citations',
        tab: 'diligence',
        targetElementId: 'latest-submission-section',
        targetSelector: '#latest-submission-section, [data-latest-submission], #history-table',
        tag: 'Step 3 • Fact Sheets & OCR',
        badge: 'Verified Line Items',
        narrative: 'Every uploaded document produces a verified financial fact sheet with exact line-item citations, OCR confidence levels, and version audit timestamps (e.g. $15.8M Revenue, $3.2M EBITDA, Math Checks Passed).',
        proTip: 'Click any extracted metric in the workspace to inspect its underlying source document coordinate.',
        keyTakeaway: 'Zero numeric hallucination guarantee via strict per-doc extraction and math check audit.',
        cursorPlacement: 'top-left',
        durationMs: 13000,
    },
    {
        id: 'core-step-4',
        num: 4,
        title: 'Multi-Document Synthesis & EBITDA Normalization',
        tab: 'synthesis',
        targetElementId: 'synthesis-judgment',
        targetSelector: '#synthesis-judgment, #diligence-project-synth, [data-synthesis-judgment]',
        tag: 'Step 4 • Deal Synthesis',
        badge: 'EBITDA & Valuation',
        narrative: 'Cross-reconcile contradictory figures across all 4 documents. Dillon AI normalizes owner add-backs ($450k salary, $120k legal), flags customer concentration (>35%), and calculates an institutional valuation range (Bear $10.8M / Base $13.5M / Bull $15.2M).',
        proTip: 'Automated cross-document contradiction detection reconciles seller marketing claims against IRS tax filings.',
        keyTakeaway: 'Instant multi-doc reconciliation and institutional valuation spread calculation.',
        cursorPlacement: 'center',
        durationMs: 14000,
    },
    {
        id: 'core-step-5',
        num: 5,
        title: 'Executive Deal Memo & Deal-on-a-Page Scorecard',
        tab: 'overview',
        targetElementId: 'overview-snapshot',
        targetSelector: '#overview-snapshot, #deal-workspace, main',
        tag: 'Step 5 • Executive Memo',
        badge: 'Deal-on-a-Page',
        narrative: 'Consolidates all findings into an executive Deal-on-a-Page: verified revenue ($15.8M), EBITDA margin (20.3%), purchase multiple vs market ceiling, composite 0-100 health score (88/100), and institutional IC judgment (PROCEED WITH CONDITIONS).',
        proTip: 'Executive single-pane summary ready for PE partners, lenders, and search fund investors.',
        keyTakeaway: 'Actionable executive synthesis for PE partners, lenders, and search funds.',
        cursorPlacement: 'center',
        durationMs: 13000,
    },
    {
        id: 'core-step-6',
        num: 6,
        title: 'Ask Dillon AI Copilot & 1-Click Workspace Links',
        tab: 'overview',
        targetElementId: 'deal-chat-dock',
        targetSelector: '#deal-chat-dock, [data-chat-card], [data-chat-trigger]',
        tag: 'Step 6 • AI Deal Copilot',
        badge: '3-Tier Routing',
        narrative: 'Open Dillon AI to ask natural language diligence questions (e.g. "What is the DSCR?", "Explain EBITDA add-backs", "Draft broker pushback"). Dillon AI grounds every answer in deal facts and provides 1-click links into workspace cards.',
        proTip: 'Powered by 3-tier intelligent routing: Cloud AI Webhook → Direct User LLM → Local Deterministic Engine.',
        keyTakeaway: 'Snappy, grounded AI due diligence advisor with zero hallucination risk.',
        simulatedAction: {
            type: 'type_chat',
            payload: 'What are the main red flags and debt service coverage for this target?',
        },
        cursorPlacement: 'bottom-right',
        durationMs: 14000,
    },
    {
        id: 'core-step-7',
        num: 7,
        title: 'Export Investment Committee Diligence Package',
        tab: 'overview',
        targetElementId: 'export-deal-btn',
        targetSelector: '#export-deal-btn, button[data-export-btn], button:has(svg.lucide-file-text)',
        tag: 'Step 7 • IC Memo Export',
        badge: 'Publication Ready',
        narrative: 'Download publication-ready Investment Committee memorandums and audit-grade deal packages in Markdown, PDF, or JSON, powered by enterprise cloud workflows ready for lenders, LPs, and investment committees.',
        proTip: '1-click export packages all citations, QoE adjustments, and valuation models into audit-grade deliverables.',
        keyTakeaway: '100% audit transparency ready for lenders and investment committees.',
        cursorPlacement: 'top-right',
        durationMs: 12000,
    },
]

export const DEEP_DIVE_STEPS: WalkthroughStep[] = [
    {
        id: 'deep-step-1',
        num: 1,
        title: 'Multi-Doc Deal Room Ingestion',
        tab: 'diligence',
        targetElementId: 'project-intake',
        targetSelector: '[data-project-intake]',
        tag: 'Intake',
        badge: 'Deal Room',
        narrative: 'Upload CIMs, signed LOIs, 2-year tax returns, and QuickBooks balance sheets simultaneously into the secure isolated intake vault.',
        keyTakeaway: 'Multi-file parallel queue with auto-detected document classification.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-2',
        num: 2,
        title: 'Deterministic OCR & Extraction Pipeline',
        tab: 'diligence',
        targetElementId: 'project-intake',
        targetSelector: '[data-project-intake]',
        tag: 'Ingestion',
        badge: 'Multi-Model AI',
        narrative: 'Our multi-model extraction pipeline parses scanned PDFs and multi-tab spreadsheets into structured JSON schemas with full cell coordinate mapping.',
        keyTakeaway: 'Per-document extraction primary model powered by OpenAI 5.6 Terra.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-3',
        num: 3,
        title: 'Submission History & Version Audit Trail',
        tab: 'history',
        targetElementId: 'history-table',
        tag: 'Audit Trail',
        badge: 'Provenance',
        narrative: 'Inspect all historical document versions, extraction processing times, tokens consumed, and extraction status across all deal runs.',
        keyTakeaway: 'Full chronological ledger for every document run.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-4',
        num: 4,
        title: 'LOI Terms & Purchase Price Extraction',
        tab: 'analysis',
        targetElementId: 'analysis-deal-on-a-page',
        tag: 'LOI Terms',
        badge: 'Core Terms',
        narrative: 'Extracts purchase price, earnout milestones, seller financing rates, and closing contingencies directly from the executed Letter of Intent.',
        keyTakeaway: 'Locks in agreed baseline terms vs seller marketing teasers.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-5',
        num: 5,
        title: '100% Ground Truth Evidence & Citations',
        tab: 'analysis',
        targetElementId: 'analysis-scorecard',
        tag: 'Citations',
        badge: 'Ground Truth',
        narrative: 'Every single extracted financial metric links directly to its source document, page number, and original table bounding box.',
        keyTakeaway: 'Click any metric in the workspace to inspect its underlying document proof.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-6',
        num: 6,
        title: 'Verified SDE & EBITDA Add-Backs',
        tab: 'analysis',
        targetElementId: 'analysis-qoe',
        tag: 'Quality of Earnings',
        badge: 'QoE Adjustments',
        narrative: 'Reconciles discretionary expenses, non-arm’s-length officer salaries, and one-time consulting fees against IRS guidelines.',
        keyTakeaway: 'Separates confirmed add-backs from unsubstantiated seller claims.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-7',
        num: 7,
        title: 'Enterprise Value Implied by Asking Price',
        tab: 'valuation',
        targetElementId: 'valuation-comps',
        tag: 'Valuation',
        badge: 'Implied Multiple',
        narrative: 'Calculates headline Enterprise Value multiple against normalized earnings and contrasts it against actual lower-middle-market deal comps.',
        keyTakeaway: 'Instantly surfaces seller premium over historical sector transactions.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-8',
        num: 8,
        title: 'Debt-to-Asset & Solvency Audit',
        tab: 'analysis',
        targetElementId: 'analysis-snapshot',
        tag: 'Balance Sheet',
        badge: 'Solvency Health',
        narrative: 'Cross-checks balance sheet current assets against funded obligations to ensure the target business is liquid and solvent.',
        keyTakeaway: 'Verifies healthy debt-to-asset ratios before committing lender capital.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-9',
        num: 9,
        title: 'Cross-Document Contradiction Reconciliation',
        tab: 'analysis',
        targetElementId: 'analysis-coverage',
        tag: 'Reconciliation',
        badge: 'Contradiction Detector',
        narrative: 'Identifies discrepancies between broker teaser decks and audited tax returns (e.g. $4.8M reported revenue vs $4.2M on IRS 1120-S).',
        keyTakeaway: 'Surfaces hidden variance before entering formal exclusivity.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-10',
        num: 10,
        title: 'Customer Concentration Red Flag Analysis',
        tab: 'analysis',
        targetElementId: 'analysis-risk-valuation',
        tag: 'Risk Analysis',
        badge: 'Customer Concentration',
        narrative: 'Evaluates top customer revenue share. Deals with top-client concentration over 30% are flagged for escrow indemnity and earnout restructuring.',
        keyTakeaway: 'Calculates maximum single-point-of-failure revenue risk.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-11',
        num: 11,
        title: 'Cross-Doc Synthesis & $350k Escrow Holdback',
        tab: 'overview',
        targetElementId: 'synthesis-judgment',
        tag: 'Synthesis',
        badge: 'Holdback Engine',
        narrative: 'Multi-document synthesis engine computes specific contractual dollar holdbacks (e.g., $350,000 indemnification holdback for 18 months).',
        keyTakeaway: 'Translates analytical risk into enforceable purchase agreement clauses.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-12',
        num: 12,
        title: 'Key Management Diligence Questions',
        tab: 'overview',
        targetElementId: 'synthesis-next-step',
        tag: 'Management Q&A',
        badge: 'Management Interview',
        narrative: 'Auto-generates high-leverage confirmatory questions tailored for management interviews on vendor contracts and customer churn.',
        keyTakeaway: 'Empowers buyers with senior diligence interview scripts.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-13',
        num: 13,
        title: 'Critical Cash Flow & Margin Pressure Alerts',
        tab: 'overview',
        targetElementId: 'synthesis-valuation',
        tag: 'Cash Flow',
        badge: 'Margin Degradation',
        narrative: 'Alerts the deal team to gross margin compression or working capital seasonality that could impair debt service post-acquisition.',
        keyTakeaway: 'Early warning engine against post-close liquidity crunches.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-14',
        num: 14,
        title: 'Investment Committee ESCALATE Verdict',
        tab: 'overview',
        targetElementId: 'synthesis-judgment',
        tag: 'Verdict',
        badge: 'Committee Summary',
        narrative: 'Packages all red flags, multiple disconnects, and normalized EBITDA into an institutional PE summary verdict for deal partners.',
        keyTakeaway: 'Clear GO / NO-GO / RE-TRADE recommendation.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-15',
        num: 15,
        title: 'Enterprise Value Methodologies & Bridge',
        tab: 'valuation',
        targetElementId: 'valuation-comps',
        tag: 'Valuation Bridge',
        badge: 'EV Mechanics',
        narrative: 'Examines Enterprise Value calculation mechanics: EV = Headline Purchase Price + Net Funded Debt − Closing Cash.',
        keyTakeaway: 'Unpacks exact debt and cash adjustments across all scenarios.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-16',
        num: 16,
        title: 'Normalized Valuation Multiples Breakdown',
        tab: 'valuation',
        targetElementId: 'valuation-comps',
        tag: 'Multiples Matrix',
        badge: 'Bear / Base / Bull',
        narrative: 'Models dynamic valuation sensitivity across 3.0x Bear, 4.0x Base, and 5.0x Bull multiples based on target company quality.',
        keyTakeaway: 'Determines downside floor and upside potential before bidding.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-17',
        num: 17,
        title: 'Breakeven Analysis & Fixed Cost Absorption',
        tab: 'analysis',
        targetElementId: 'analysis-breakeven',
        tag: 'Breakeven',
        badge: 'Fixed vs Variable',
        narrative: 'Calculates the exact revenue breakeven threshold and margin of safety required to cover operating overhead and debt service.',
        keyTakeaway: 'Answers: How much can revenue drop before the business loses money?',
        durationMs: 6500,
    },
    {
        id: 'deep-step-18',
        num: 18,
        title: 'Monte Carlo Simulation (1,000 Iterations)',
        tab: 'analysis',
        targetElementId: 'analysis-monte-carlo',
        tag: 'Monte Carlo',
        badge: 'Stochastic Simulation',
        narrative: 'Simulates 1,000 stochastic economic outcomes across revenue growth, margin volatility, and exit multiples to compute probability of loss.',
        keyTakeaway: 'Rigorous risk quantification beyond simple static models.',
        durationMs: 7000,
    },
    {
        id: 'deep-step-19',
        num: 19,
        title: 'Opportunity & Revenue Upside Levers',
        tab: 'growth',
        targetElementId: 'growth-scenarios',
        targetSelector: '#growth-scenarios, #analysis-opportunity',
        tag: 'Growth Plan',
        badge: 'Value Creation',
        narrative: 'Identifies post-acquisition value creation opportunities: pricing power adjustments, sales team expansion, and cross-selling.',
        keyTakeaway: 'Clear 100-day operational roadmap to expand equity value.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-20',
        num: 20,
        title: 'Dillon AI Deal Copilot Context Integration',
        tab: 'overview',
        targetElementId: 'deal-chat-dock',
        targetSelector: 'button[title*="Chat"], [data-chat-trigger]',
        tag: 'Deal Copilot',
        badge: 'AI Assistant',
        narrative: 'Dillon AI ingests the full workspace financial model, OCR citations, and red flags into its active system prompt for real-time intelligence.',
        keyTakeaway: 'Zero generic hallucinations — every answer cites live project facts.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-21',
        num: 21,
        title: 'Grounded Copilot Deal Q&A & Calculations',
        tab: 'overview',
        targetElementId: 'deal-chat-dock',
        targetSelector: 'button[title*="Chat"], [data-chat-trigger]',
        tag: 'Copilot Q&A',
        badge: 'Deep Linking',
        narrative: 'Ask complex questions like: "What is the DSCR under a 10.5% interest rate?" or "Where is the breakeven chart?" with instant deep links.',
        keyTakeaway: 'Interactive AI answers with 1-click workspace navigation links.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-22',
        num: 22,
        title: '1-Click Broker Negotiation & Pushback Scripts',
        tab: 'negotiation',
        targetElementId: 'negotiation-levers',
        targetSelector: '#negotiation-levers, #analysis-term-sheet',
        tag: 'Broker Scripts',
        badge: 'Email Generator',
        narrative: 'Generates polite, professional broker pushback letters highlighting valuation gaps and asking for detailed customer concentration schedules.',
        keyTakeaway: 'Instant negotiation leverage backed by empirical findings.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-23',
        num: 23,
        title: 'Senior Debt Sizing & SBA 7(a) Limits',
        tab: 'structure',
        targetElementId: 'structure-dscr',
        targetSelector: '#structure-dscr, #structure-sources-uses',
        tag: 'Senior Debt',
        badge: 'SBA 7(a) Modeling',
        narrative: 'Models maximum $5.0M SBA 7(a) senior debt limits, 10-year amortization curves, and current prime-plus interest rate assumptions.',
        keyTakeaway: 'Ensures deal structure complies with SBA lending standards.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-24',
        num: 24,
        title: 'Seller Note Subordination & Standstill Terms',
        tab: 'structure',
        targetElementId: 'structure-sources-uses',
        targetSelector: '#structure-sources-uses, #returns-waterfall',
        tag: 'Seller Note',
        badge: 'Subordination',
        narrative: 'Structures a 10% to 15% seller promissory note with a 24-month payment standstill to qualify for SBA equity injection rules.',
        keyTakeaway: 'Bridges valuation gaps while minimizing buyer cash out of pocket.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-25',
        num: 25,
        title: 'Working Capital Peg & Closing True-Up Rules',
        tab: 'analysis',
        targetElementId: 'analysis-rules',
        targetSelector: '#analysis-rules, #analysis-snapshot',
        tag: 'Working Capital',
        badge: 'Peg Definition',
        narrative: 'Defines the Target Net Working Capital (NWC) Peg based on 12-month trailing averages to prevent seller cash stripping before closing.',
        keyTakeaway: 'Prevents post-closing disputes over accounts receivable and inventory.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-26',
        num: 26,
        title: '5-Year Levered Equity Waterfall & IRR Matrix',
        tab: 'returns',
        targetElementId: 'returns-waterfall',
        targetSelector: '#returns-waterfall, #returns-irr',
        tag: 'Returns Waterfall',
        badge: 'IRR & MOIC',
        narrative: 'Models 5-year levered equity returns, cash-on-cash yield, debt paydown equity buildup, and exit multiples to calculate final investor IRR.',
        keyTakeaway: 'Institutional returns analysis for PE sponsors and search funds.',
        durationMs: 7000,
    },
    {
        id: 'deep-step-27',
        num: 27,
        title: 'Phase II Due Diligence Confirmatory Checklist',
        tab: 'diagnostics',
        targetElementId: 'checklist-section',
        targetSelector: '#checklist-section, #analysis-coverage',
        tag: 'Checklist',
        badge: 'Confirmatory DD',
        narrative: 'Generates a 30-item customized diligence request list (Phase II DD) covering tax compliance, key employee agreements, and IP assignments.',
        keyTakeaway: 'Exhaustive legal and financial verification before definitive signing.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-28',
        num: 28,
        title: 'Publication-Ready IC Memo & Full Export',
        tab: 'overview',
        targetElementId: 'export-deal-btn',
        targetSelector: 'button:has(svg.lucide-file-text), [data-export-btn]',
        tag: 'IC Memo Export',
        badge: 'Final Deliverable',
        narrative: 'Export complete audit packages and Investment Committee memos in markdown and PDF formats with full chart snapshots and provenance tags.',
        keyTakeaway: 'Professional, defensible diligence ready for institutional signoff.',
        durationMs: 7000,
    },
]

export const QUEST_MISSIONS: WalkthroughStep[] = [
    {
        id: 'quest-step-1',
        num: 1,
        title: 'Mission 1: The Valuation Gap Detective',
        tab: 'valuation',
        targetElementId: 'valuation-comps',
        targetSelector: '#valuation-comps, [data-valuation-comps], #valuation-summary',
        tag: 'Quest 1',
        badge: 'Valuation Detective',
        narrative: 'The seller is asking for $5.0M, which represents a 7.9x multiple on reported earnings. Market comps for this sector top out at 4.2x.',
        keyTakeaway: 'Explore the valuation band and observe the implied discount.',
        questPrompt: {
            instruction: 'Switch to the Valuation tab and review the Bear vs Base vs Bull multiple spread.',
            hint: 'Click on the Valuation tab in the top navigation bar.',
            triggerType: 'tab_change',
            expectedValue: 'valuation',
        },
        durationMs: 12000,
    },
    {
        id: 'quest-step-2',
        num: 2,
        title: 'Mission 2: Inspecting QoE Add-Backs',
        tab: 'analysis',
        targetElementId: 'analysis-qoe',
        targetSelector: '#analysis-qoe, #analysis-ebitda-quality, [data-analysis-qoe]',
        tag: 'Quest 2',
        badge: 'QoE Auditor',
        narrative: 'The seller claimed $142k in discretionary adjustments. Inspect the Quality of Earnings table to identify unverified items.',
        keyTakeaway: 'Verify owner compensation and discretionary expenses.',
        questPrompt: {
            instruction: 'Navigate to the Analysis tab to examine the Quality of Earnings breakdown.',
            hint: 'Click the Analysis tab to view the EBITDA reconciliation table.',
            triggerType: 'tab_change',
            expectedValue: 'analysis',
        },
        durationMs: 12000,
    },
    {
        id: 'quest-step-3',
        num: 3,
        title: 'Mission 3: Testing Debt Service Coverage',
        tab: 'structure',
        targetElementId: 'structure-dscr',
        targetSelector: '#structure-dscr, [data-structure-dscr], #structure-leverage, [data-structure-leverage], #structure-visual',
        tag: 'Quest 3',
        badge: 'Lender Sizing',
        narrative: 'Lenders require a minimum DSCR of 1.25x. At 1.38x, this deal meets Senior SBA guidelines with a modest safety cushion.',
        keyTakeaway: 'Check debt service coverage under various interest rate assumptions.',
        questPrompt: {
            instruction: 'Navigate to Deal Structure to inspect the DSCR coverage ratio.',
            hint: 'Click on Deal Structure in the top navigation bar.',
            triggerType: 'tab_change',
            expectedValue: 'structure',
        },
        durationMs: 12000,
    },
    {
        id: 'quest-step-4',
        num: 4,
        title: 'Mission 4: Interrogating Dillon AI Copilot',
        tab: 'overview',
        targetElementId: 'deal-chat-dock',
        targetSelector: '#deal-chat-dock, [data-chat-trigger], [data-chat-card], button[title*="Chat"]',
        tag: 'Quest 4',
        badge: 'AI Investigator',
        narrative: 'Dillon AI is connected to all uploaded deal documents and models. Ask any diligence question or ask for an executive deal memo.',
        keyTakeaway: 'Use natural-language prompts to uncover risks and draft emails.',
        questPrompt: {
            instruction: 'Open the Dillon AI Deal Copilot panel on the right side of the screen.',
            hint: 'Click the Dillon AI Chat button in the bottom-right corner.',
            triggerType: 'click_target',
        },
        durationMs: 12000,
    },
    {
        id: 'quest-step-5',
        num: 5,
        title: 'Mission 5: Exporting the Investment Memo',
        tab: 'overview',
        targetElementId: 'export-deal-btn',
        targetSelector: '#export-deal-btn, #export-memo-btn, [data-export-btn], button:has(svg.lucide-file-down)',
        tag: 'Quest 5',
        badge: 'Deal Closer',
        narrative: 'Congratulations! You have inspected the deal terms, validated the earnings, and evaluated debt sizing. You are ready to export the deal packet.',
        keyTakeaway: '1-click export for partners, lenders, and investment committees.',
        questPrompt: {
            instruction: 'Review the Export Deal button in the top header to see export options.',
            hint: 'Look for Export Deal in the top-right header.',
            triggerType: 'tab_change',
            expectedValue: 'overview',
        },
        durationMs: 12000,
    },
]

export const TOUR_PLAYLISTS: Record<string, TourPlaylist> = {
    'core-fast': {
        id: 'core-fast',
        title: 'Guided Walkthrough #1: End-to-End Diligence Workflow',
        subtitle: 'Core deal workflow: Staging → Parallel Batch → Fact Sheets → Synthesis → Overview → Chatbot → Export (~90 sec)',
        durationLabel: '~90 sec',
        stepCount: CORE_FAST_STEPS.length,
        iconName: 'Zap',
        color: 'from-blue-600 to-indigo-600',
        description: 'The authentic M&A diligence journey: Staging deal room documents, parallel batch extraction, verified fact sheets, multi-doc synthesis, executive IC memo, Dillon AI copilot, and package export.',
        steps: CORE_FAST_STEPS,
    },
    'deep-dive': {
        id: 'deep-dive',
        title: 'Guided Walkthrough #2: Deep Financial & Platform Tour',
        subtitle: 'Institutional multi-tab analysis & deal structuring (~3-4 mins)',
        durationLabel: '~3.5 min',
        stepCount: DEEP_DIVE_STEPS.length,
        iconName: 'Layers',
        color: 'from-emerald-600 to-teal-600',
        description: 'An exhaustive masterclass inspecting valuation comps spreads, EBITDA add-backs & QoE, solvency tests, customer concentration, debt sizing, and error diagnostic harnesses.',
        steps: DEEP_DIVE_STEPS,
    },
    'interactive-quest': {
        id: 'interactive-quest',
        title: 'Interactive Hands-On Quest',
        subtitle: 'Gamified diligence missions (learn by doing)',
        durationLabel: 'Self-Paced',
        stepCount: QUEST_MISSIONS.length,
        iconName: 'Target',
        color: 'from-amber-500 to-orange-600',
        description: 'Interactive quest mode with real hands-on missions. Complete each challenge to master valuation modeling, add-back audits, and deal negotiation.',
        steps: QUEST_MISSIONS,
    },
}

import type { WorkspaceTab } from '../DealWorkspaceNav'

export const TAB_TOUR_STEPS: Record<WorkspaceTab, WalkthroughStep[]> = {
    overview: [
        {
            id: 'overview-step-1',
            num: 1,
            title: 'Executive Deal Snapshot & Fundamentals',
            tab: 'overview',
            targetElementId: 'overview-snapshot',
            targetSelector: '#overview-snapshot',
            tag: 'Executive Summary',
            badge: 'Deal Snapshot',
            narrative: 'The Deal on a Page snapshot aggregates the target company fundamentals: headline revenue, normalized EBITDA, asking price, and verified valuation multiple in an executive card.',
            keyTakeaway: 'High-level financial overview providing immediate orientation for investment committees.',
            cursorPlacement: 'top-left',
            durationMs: 7000,
        },
        {
            id: 'overview-step-2',
            num: 2,
            title: 'Composite Deal Health Scorecard',
            tab: 'overview',
            targetElementId: 'overview-health',
            targetSelector: '#overview-health',
            tag: 'Health Scorecard',
            badge: '0-100 Index',
            narrative: 'A 0-100 composite index measuring earnings quality, customer concentration, balance sheet leverage, and margin stability to provide a quick traffic-light health assessment.',
            keyTakeaway: 'Institutional multi-factor rating benchmarking target viability.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'overview-step-3',
            num: 3,
            title: 'Priority Diligence Action Items & Gating',
            tab: 'overview',
            targetElementId: 'overview-actions',
            targetSelector: '#overview-actions',
            tag: 'Action Plan',
            badge: 'Gating Items',
            narrative: 'Highlights critical gating items requiring buyer resolution before LOI expiration, including escrow holdbacks, tax return reconciliations, and key customer interviews.',
            keyTakeaway: 'Prioritizes high-stakes diligence tasks to avoid closing delays.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'overview-step-4',
            num: 4,
            title: 'Acquisition Closing Roadmap & Milestones',
            tab: 'overview',
            targetElementId: 'overview-timeline',
            targetSelector: '#overview-timeline',
            tag: 'Transaction Timeline',
            badge: 'Milestones',
            narrative: 'Tracks the end-to-end acquisition lifecycle across Phase I intake, Quality of Earnings audit, bank underwriting, definitive agreements, and Day 1 closing handover.',
            keyTakeaway: 'Clear phase-by-phase visibility through transaction closing.',
            cursorPlacement: 'bottom-left',
            durationMs: 7000,
        },
    ],
    analysis: [
        {
            id: 'analysis-step-1',
            num: 1,
            title: 'Deal on a Page Executive Card',
            tab: 'analysis',
            targetElementId: 'analysis-deal-on-a-page',
            targetSelector: '#analysis-deal-on-a-page',
            tag: 'Executive QoE',
            badge: 'Deal on a Page',
            narrative: 'Single-pane executive card synthesizing key transaction financial metrics, asking vs fair market value multiple, and immediate deal status.',
            keyTakeaway: 'Executive orientation for deep-dive Quality of Earnings analysis.',
            cursorPlacement: 'top-left',
            durationMs: 7000,
        },
        {
            id: 'analysis-step-2',
            num: 2,
            title: 'Deal Scorecard & Opportunity Matrix',
            tab: 'analysis',
            targetElementId: 'analysis-scorecard',
            targetSelector: '#analysis-scorecard',
            tag: 'Scorecard',
            badge: 'Deal Score',
            narrative: 'Evaluates the acquisition target across financial health, margin expansion, moat strength, and risk resilience with weighted sub-scores.',
            keyTakeaway: 'Quantitative rating benchmarked against historical transactions.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'analysis-step-3',
            num: 3,
            title: 'EBITDA Reconstruction & Quality of Earnings Bridge',
            tab: 'analysis',
            targetElementId: 'analysis-ebitda-quality',
            targetSelector: '#analysis-ebitda-quality, [data-analysis-qoe]',
            tag: 'Quality of Earnings',
            badge: 'QoE Waterfall',
            narrative: 'Reconstructs reported net income to adjusted EBITDA, systematically auditing seller add-backs (owner compensation, non-operating travel, one-off legal fees) to establish true cash earnings.',
            keyTakeaway: 'Identifies unsupported add-backs to protect buyer valuation.',
            cursorPlacement: 'center',
            durationMs: 7500,
        },
        {
            id: 'analysis-step-4',
            num: 4,
            title: 'Risk-Adjusted Valuation Matrix',
            tab: 'analysis',
            targetElementId: 'analysis-risk-valuation',
            targetSelector: '#analysis-risk-valuation',
            tag: 'Valuation Bridge',
            badge: 'Risk Discount',
            narrative: 'Compares seller asking valuation against risk-adjusted fair market value, accounting for customer concentration, margin volatility, and capital expenditure requirements.',
            keyTakeaway: 'Data-driven bridge supporting purchase price adjustments.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'analysis-step-5',
            num: 5,
            title: 'Breakeven Revenue & Operating Leverage',
            tab: 'analysis',
            targetElementId: 'analysis-breakeven',
            targetSelector: '#analysis-breakeven',
            tag: 'Financial Stress Test',
            badge: 'Breakeven',
            narrative: 'Calculates the minimum required revenue to cover operating expenses and debt service, stress-testing margin of safety against potential post-close revenue contractions.',
            keyTakeaway: 'Ensures target has adequate downside buffer to service acquisition debt.',
            cursorPlacement: 'bottom-left',
            durationMs: 7000,
        },
    ],
    diagnostics: [
        {
            id: 'diag-step-1',
            num: 1,
            title: 'Diligence Quick Insights & Thesis',
            tab: 'diagnostics',
            targetElementId: 'diag-quick-insights',
            targetSelector: '#diag-quick-insights',
            tag: 'Risk Diagnostics',
            badge: 'Quick Insights',
            narrative: 'Instant summary of core investment strengths, red flags, and primary underwriting takeaways generated by cross-referencing all data room materials.',
            keyTakeaway: 'Rapid synthesis of investment thesis and core vulnerabilities.',
            cursorPlacement: 'top-left',
            durationMs: 7000,
        },
        {
            id: 'diag-step-2',
            num: 2,
            title: 'Interactive Risk Heatmap Matrix',
            tab: 'diagnostics',
            targetElementId: 'diag-risk-matrix',
            targetSelector: '#diag-risk-matrix',
            tag: 'Risk Heatmap',
            badge: 'Risk Matrix',
            narrative: 'Comprehensive multi-category matrix sorting Financial, Legal, Operational, and Market risks into High, Medium, and Low severity tiers with mitigation recommendations.',
            keyTakeaway: 'Structured visibility into deal risks and contractual mitigations.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'diag-step-3',
            num: 3,
            title: 'Owner Dependency & Key Person Analysis',
            tab: 'diagnostics',
            targetElementId: 'diag-key-person',
            targetSelector: '#diag-key-person',
            tag: 'Operational Risk',
            badge: 'Key Person',
            narrative: 'Assesses operational vulnerability to founder departure, client relationship ownership, technical knowledge concentration, and transition training requirements.',
            keyTakeaway: 'Determines required seller transition period and consulting agreements.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'diag-step-4',
            num: 4,
            title: 'Phase II Diligence Request List & Tracker',
            tab: 'diagnostics',
            targetElementId: 'diag-dd-requests',
            targetSelector: '#diag-dd-requests',
            tag: 'DD Tracker',
            badge: 'Request List',
            narrative: 'Prioritized audit checklist of follow-up document requests, customer contract verifications, and CPA audit schedules for seller management.',
            keyTakeaway: 'Streamlines Phase II data room requests and broker follow-ups.',
            cursorPlacement: 'bottom-left',
            durationMs: 7000,
        },
    ],
    diligence: [
        {
            id: 'diligence-step-1',
            num: 1,
            title: 'Batch Drag-and-Drop Ingestion Vault',
            tab: 'diligence',
            targetElementId: 'project-intake',
            targetSelector: '[data-project-intake], #diligence-workspace',
            tag: 'Data Room',
            badge: 'File Intake',
            narrative: 'Securely upload P&L spreadsheets, federal tax returns, confidential information memorandums (CIMs), and LOIs in batch mode with automatic categorization.',
            keyTakeaway: 'Supports multi-file PDF, Excel, and Word ingestion.',
            cursorPlacement: 'top-left',
            durationMs: 7000,
        },
        {
            id: 'diligence-step-2',
            num: 2,
            title: 'Deterministic Table Extraction & OCR',
            tab: 'diligence',
            targetElementId: 'diligence-project-synth',
            targetSelector: '#diligence-project-synth, [data-project-intake]',
            tag: 'Extraction Engine',
            badge: 'OCR & Parsing',
            narrative: 'Extracts tabular line items, revenue streams, officer compensation, and depreciation schedules with 100% ground-truth document coordinate citations.',
            keyTakeaway: 'Zero numeric hallucination via strict document extraction.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'diligence-step-3',
            num: 3,
            title: 'Reconciliation Engine & Data Quality Checks',
            tab: 'diligence',
            targetElementId: 'diligence-quality',
            targetSelector: '#diligence-quality',
            tag: 'Data Quality',
            badge: 'Reconciliation',
            narrative: 'Automatically cross-checks tax returns against internal financial statements, flagging revenue discrepancies, unrecorded liabilities, and accounting variances.',
            keyTakeaway: 'Verifies book-to-tax reconciliation before modeling.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'diligence-step-4',
            num: 4,
            title: 'Synthesis Readiness Gate & Execution',
            tab: 'diligence',
            targetElementId: 'diligence-documents',
            targetSelector: '#diligence-documents',
            tag: 'Readiness Gate',
            badge: 'Trigger Synthesis',
            narrative: 'Verifies that all mandatory deal files have completed deterministic extraction before unlocking the multi-document AI synthesis pass.',
            keyTakeaway: 'Ensures complete data integrity prior to investment committee review.',
            cursorPlacement: 'bottom-left',
            durationMs: 7000,
        },
    ],
    synthesis: [
        {
            id: 'synthesis-step-1',
            num: 1,
            title: 'Authoritative Acquisition Judgment',
            tab: 'synthesis',
            targetElementId: 'synthesis-judgment',
            targetSelector: '#synthesis-judgment, #project-synthesis',
            tag: 'Investment Committee',
            badge: 'Deal Verdict',
            narrative: 'Consolidated multi-document verdict delivering a clear PROCEED, RE-TRADE, or PASS judgment backed by quantitative valuation bridges and risk thresholds.',
            keyTakeaway: 'Authoritative deal verdict for investment committee presentation.',
            cursorPlacement: 'top-left',
            durationMs: 7500,
        },
        {
            id: 'synthesis-step-2',
            num: 2,
            title: 'Material Diligence Findings & Red Flags',
            tab: 'synthesis',
            targetElementId: 'synthesis-material-impact',
            targetSelector: '#synthesis-material-impact',
            tag: 'Material Findings',
            badge: 'Red & Yellow Flags',
            narrative: 'Categorized catalog of material deal risks, including customer churn trends, supplier concentration, working capital pegs, and unrecorded lease obligations.',
            keyTakeaway: 'Direct empirical citations linked to underlying data room pages.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'synthesis-step-3',
            num: 3,
            title: 'Cross-Document Conflict Detector',
            tab: 'synthesis',
            targetElementId: 'synthesis-conflicts',
            targetSelector: '#synthesis-conflicts',
            tag: 'Conflict Engine',
            badge: 'Document Discrepancies',
            narrative: 'Identifies direct contradictions between seller CIM representations, tax return filings (IRS 1120-S / 1065), and management monthly financial statements.',
            keyTakeaway: 'Prevents reliance on unverified broker marketing claims.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'synthesis-step-4',
            num: 4,
            title: 'Strategic Negotiation Levers & Price Adjustments',
            tab: 'synthesis',
            targetElementId: 'synthesis-negotiation',
            targetSelector: '#synthesis-negotiation',
            tag: 'Negotiation Strategy',
            badge: 'Price Reductions',
            narrative: 'Translates verified diligence findings into specific dollar adjustments, indemnity escrow holdbacks, and earnout structures for buyer counsel and brokers.',
            keyTakeaway: 'Gives buyers concrete mathematical leverage to re-trade purchase price.',
            cursorPlacement: 'bottom-left',
            durationMs: 7000,
        },
    ],
    spending: [
        {
            id: 'spending-step-1',
            num: 1,
            title: 'AI Compute & Cloud Cost Breakdown',
            tab: 'spending',
            targetElementId: 'spending-header',
            targetSelector: '#spending-header',
            tag: 'Operations',
            badge: 'Cost Breakdown',
            narrative: 'Real-time telemetry tracking extraction compute, OCR costs, and LLM inference spend across OpenAI 5.6 Terra, OpenAI 5.6 Sol, and Project Synthesis.',
            keyTakeaway: 'Full visibility into cloud compute and model inference costs.',
            cursorPlacement: 'top-left',
            durationMs: 7000,
        },
        {
            id: 'spending-step-2',
            num: 2,
            title: 'Token Velocity & Top Spend Drivers',
            tab: 'spending',
            targetElementId: 'spending-breakdown',
            targetSelector: '#spending-breakdown',
            tag: 'Cost Optimization',
            badge: 'Spend Drivers',
            narrative: 'Identifies primary token consumption drivers, prompt caching efficiency, and empirical >50% cost reductions achieved via prompt optimization.',
            keyTakeaway: 'Monitors unit economics per document and diligence run.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'spending-step-3',
            num: 3,
            title: 'Itemized Token Ledger & Audit Log',
            tab: 'spending',
            targetElementId: 'spending-history',
            targetSelector: '#spending-history',
            tag: 'Billing Ledger',
            badge: 'Itemized Log',
            narrative: 'Comprehensive transaction ledger recording every single document processing run, input/output tokens, duration, and exact dollar cost.',
            keyTakeaway: 'Audit-ready billing ledger for deal expense attribution.',
            cursorPlacement: 'bottom-left',
            durationMs: 7000,
        },
    ],
    compare: [
        {
            id: 'compare-step-1',
            num: 1,
            title: 'Multi-Deal Portfolio Comparison Matrix',
            tab: 'compare',
            targetElementId: 'compare-table',
            targetSelector: '#compare-table, #project-comparison',
            tag: 'Portfolio Matrix',
            badge: 'Side-by-Side',
            narrative: 'Benchmark multiple acquisition targets side-by-side on revenue, EBITDA margins, asking multiples, debt sizing, and overall risk posture.',
            keyTakeaway: 'Enables rapid screening across search fund and PE deal pipelines.',
            cursorPlacement: 'top-left',
            durationMs: 7000,
        },
        {
            id: 'compare-step-2',
            num: 2,
            title: 'Relative Valuation & Multiple Benchmarks',
            tab: 'compare',
            targetElementId: 'compare-charts',
            targetSelector: '#compare-charts',
            tag: 'Valuation Comps',
            badge: 'Multiple Comparison',
            narrative: 'Visual scatter charts comparing target transaction multiples against peer industry benchmarks, identifying overvalued and undervalued opportunities.',
            keyTakeaway: 'Highlights relative pricing inefficiencies in active pipeline.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'compare-step-3',
            num: 3,
            title: 'Deal Conviction & Capital Allocation Rankings',
            tab: 'compare',
            targetElementId: 'compare-rankings',
            targetSelector: '#compare-rankings',
            tag: 'Capital Allocation',
            badge: 'Deal Rankings',
            narrative: 'Prioritizes active deals by risk-adjusted return potential, helping sponsors allocate diligence time and equity capital to highest-conviction targets.',
            keyTakeaway: 'Disciplined capital allocation for acquisition portfolios.',
            cursorPlacement: 'bottom-left',
            durationMs: 7000,
        },
    ],
    valuation: [
        {
            id: 'valuation-step-1',
            num: 1,
            title: 'Valuation Triangulation & Model Assumptions',
            tab: 'valuation',
            targetElementId: 'valuation-header',
            targetSelector: '#valuation-header',
            tag: 'Valuation Model',
            badge: 'Model Assumptions',
            narrative: 'Consolidated valuation assumptions summary displaying enterprise value inputs, adjusted EBITDA base, working capital requirements, and transaction fees.',
            keyTakeaway: 'Central hub for all financial valuation parameters.',
            cursorPlacement: 'top-left',
            durationMs: 7000,
        },
        {
            id: 'valuation-step-2',
            num: 2,
            title: 'Deal Valuation & Asking Multiple Explorer',
            tab: 'valuation',
            targetElementId: 'valuation-quick',
            targetSelector: '#valuation-quick',
            tag: 'Multiple Explorer',
            badge: 'Valuation Triangulation',
            narrative: 'Triangulates business value across Discounted Cash Flow (DCF), Precedent Transactions, and SDE Multiples with real-time slider controls.',
            keyTakeaway: 'Interactive modeling to test sensitivity to valuation multiples.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'valuation-step-3',
            num: 3,
            title: 'Valuation Gap & Pricing Disconnect Matrix',
            tab: 'valuation',
            targetElementId: 'valuation-gap',
            targetSelector: '#valuation-gap',
            tag: 'Pricing Gap',
            badge: 'Multiple Disconnect',
            narrative: 'Quantifies the exact dollar delta between seller asking price and fair market valuation, highlighting the re-trade opportunity for LOI revisions.',
            keyTakeaway: 'Provides objective basis for purchase price negotiations.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'valuation-step-4',
            num: 4,
            title: 'Comparable Transactions & Sensitivity Analysis',
            tab: 'valuation',
            targetElementId: 'valuation-comps',
            targetSelector: '#valuation-comps, #valuation-sensitivity',
            tag: 'Transaction Comps',
            badge: 'Peer Multiples',
            narrative: 'Empirical M&A comp database across Bear, Base, and Bull valuation bands paired with 2D sensitivity grids testing varying revenue growth and margin scenarios.',
            keyTakeaway: 'Defensible market comps supporting lender and equity presentations.',
            cursorPlacement: 'bottom-left',
            durationMs: 7000,
        },
    ],
    returns: [
        {
            id: 'returns-step-1',
            num: 1,
            title: 'Investor Return Metrics & Decision Summary',
            tab: 'returns',
            targetElementId: 'returns-header',
            targetSelector: '#returns-header',
            tag: 'Returns Summary',
            badge: 'IRR & MOIC',
            narrative: 'Summary of projected 5-year levered returns: Net IRR, Multiple on Invested Capital (MOIC), cumulative cash flow, and debt paydown equity accretion.',
            keyTakeaway: 'Validates target returns against fund hurdle rates (e.g., IRR >= 25%).',
            cursorPlacement: 'top-left',
            durationMs: 7000,
        },
        {
            id: 'returns-step-2',
            num: 2,
            title: 'All-Cash vs Financed Returns Waterfall',
            tab: 'returns',
            targetElementId: 'returns-all-cash',
            targetSelector: '#returns-all-cash, #returns-waterfall',
            tag: 'Return Comparison',
            badge: 'Leverage Impact',
            narrative: 'Compares unlevered all-cash returns against levered capital structures, illustrating the return enhancement provided by Senior SBA 7(a) debt.',
            keyTakeaway: 'Demonstrates the power of prudent financial leverage.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'returns-step-3',
            num: 3,
            title: 'Financing Scenario Sensitivity & Payback',
            tab: 'returns',
            targetElementId: 'returns-scenario',
            targetSelector: '#returns-scenario, #returns-payback',
            tag: 'Scenario Modeling',
            badge: 'Payback Period',
            narrative: 'Models equity payback period under Conservative, Base, and Expansion scenarios, evaluating capital preservation under adverse market conditions.',
            keyTakeaway: 'Evaluates downside risk and cash flow durability.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'returns-step-4',
            num: 4,
            title: 'Hold Period & Exit Multiple Sensitivity',
            tab: 'returns',
            targetElementId: 'returns-hold-period',
            targetSelector: '#returns-hold-period',
            tag: 'Sensitivity Grid',
            badge: 'Exit Scenarios',
            narrative: 'Two-dimensional sensitivity matrix mapping projected levered IRR across 3-to-7 year hold periods and 3.0x-to-6.0x exit valuation multiples.',
            keyTakeaway: 'Comprehensive exit matrix for limited partners and lenders.',
            cursorPlacement: 'bottom-left',
            durationMs: 7000,
        },
    ],
    growth: [
        {
            id: 'growth-step-1',
            num: 1,
            title: 'Pro Forma Revenue & EBITDA Projections',
            tab: 'growth',
            targetElementId: 'growth-header',
            targetSelector: '#growth-header, #growth-scenario',
            tag: 'Financial Model',
            badge: '5-Year Forecast',
            narrative: 'Five-year financial model forecasting revenue growth, gross margin evolution, SG&A leverage, and EBITDA expansion post-acquisition.',
            keyTakeaway: 'Builds realistic operating projections based on historical performance.',
            cursorPlacement: 'top-left',
            durationMs: 7000,
        },
        {
            id: 'growth-step-2',
            num: 2,
            title: 'Scenario Comparison & Revenue Bridge',
            tab: 'growth',
            targetElementId: 'growth-revenue-bridge',
            targetSelector: '#growth-revenue-bridge, #growth-scenario',
            tag: 'Growth Scenarios',
            badge: 'Revenue Bridge',
            narrative: 'Decomposes revenue expansion into organic volume growth, pricing optimization, new product lines, and customer churn offsets across Bear, Base, and Bull cases.',
            keyTakeaway: 'Isolates the key drivers of top-line revenue expansion.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'growth-step-3',
            num: 3,
            title: 'Value Creation Plan & Operating Leverage',
            tab: 'growth',
            targetElementId: 'growth-levers',
            targetSelector: '#growth-levers, #growth-leverage',
            tag: 'Value Creation',
            badge: 'Operating Levers',
            narrative: 'Actionable 100-day value creation roadmap identifying pricing enhancements, procurement savings, and operational leverage opportunities post-close.',
            keyTakeaway: 'Structured playbook for post-acquisition EBITDA expansion.',
            cursorPlacement: 'bottom-left',
            durationMs: 7000,
        },
    ],
    structure: [
        {
            id: 'structure-step-1',
            num: 1,
            title: 'Capital Structure & Visual Breakdown',
            tab: 'structure',
            targetElementId: 'structure-header',
            targetSelector: '#structure-header, #structure-visual',
            tag: 'Capital Structure',
            badge: 'Sources & Uses',
            narrative: 'Institutional Sources & Uses of funds balancing Senior SBA debt, seller note, rollover equity, and buyer cash equity contribution.',
            keyTakeaway: 'Ensures sources and uses balance with zero capital gap.',
            cursorPlacement: 'top-left',
            durationMs: 7000,
        },
        {
            id: 'structure-step-2',
            num: 2,
            title: 'Debt Capital Stack & Amortization',
            tab: 'structure',
            targetElementId: 'structure-stack',
            targetSelector: '#structure-stack',
            tag: 'Debt Schedule',
            badge: 'Amortization',
            narrative: 'Detailed debt schedule modeling senior debt amortization, interest rate spreads, seller note subordination, and standby agreements.',
            keyTakeaway: 'Models principal paydown and annual interest obligations.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'structure-step-3',
            num: 3,
            title: 'DSCR & Bank Covenant Safety Stress Test',
            tab: 'structure',
            targetElementId: 'structure-dscr',
            targetSelector: '#structure-dscr, #structure-leverage',
            tag: 'Covenant Safety',
            badge: 'DSCR >= 1.35x',
            narrative: 'Stress-tests Debt Service Coverage Ratio (DSCR) under 100-200 bps interest rate hikes and 10-20% revenue declines to verify SBA underwriting compliance.',
            keyTakeaway: 'Validates bank covenant cushion before lender submission.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'structure-step-4',
            num: 4,
            title: 'Working Capital & Financing Comparison',
            tab: 'structure',
            targetElementId: 'structure-financing',
            targetSelector: '#structure-financing',
            tag: 'Working Capital',
            badge: 'Working Capital Peg',
            narrative: 'Analyzes target working capital requirements at closing, calculating the required cash buffer and comparing alternative debt vs equity financing structures.',
            keyTakeaway: 'Defines target working capital peg for definitive legal agreements.',
            cursorPlacement: 'bottom-left',
            durationMs: 7000,
        },
    ],
    negotiation: [
        {
            id: 'negotiation-step-1',
            num: 1,
            title: 'Seller Diligence Questions & Inquiry Packets',
            tab: 'negotiation',
            targetElementId: 'negotiation-seller',
            targetSelector: '#negotiation-seller, #negotiation-header',
            tag: 'Seller Inquiry',
            badge: 'Q&A Packet',
            narrative: 'Pre-formatted seller management questions targeting unverified add-backs, customer concentration risks, and supplier contract terms.',
            keyTakeaway: 'Structured management interview questions grounded in diligence findings.',
            cursorPlacement: 'top-left',
            durationMs: 7000,
        },
        {
            id: 'negotiation-step-2',
            num: 2,
            title: 'Negotiation Playbook & Strategic Levers',
            tab: 'negotiation',
            targetElementId: 'negotiation-playbook',
            targetSelector: '#negotiation-playbook, #negotiation-levers',
            tag: 'Deal Strategy',
            badge: 'Negotiation Levers',
            narrative: 'Catalog of tactical negotiation levers converting identified red flags into contractual terms: indemnity escrow holdbacks, earnouts, and reps & warranties insurance.',
            keyTakeaway: 'Strategic playbook for buyer discussions with brokers and sellers.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'negotiation-step-3',
            num: 3,
            title: 'Valuation Impact Bridge & Re-Trade Levers',
            tab: 'negotiation',
            targetElementId: 'negotiation-impact',
            targetSelector: '#negotiation-impact',
            tag: 'Price Bridge',
            badge: 'Re-Trade Valuation',
            narrative: 'Mathematical waterfall quantifying recommended purchase price adjustments, justifying price concessions with empirical QoE evidence.',
            keyTakeaway: 'Empirical justification for LOI purchase price reductions.',
            cursorPlacement: 'bottom-left',
            durationMs: 7000,
        },
    ],
    documents: [
        {
            id: 'documents-step-1',
            num: 1,
            title: 'Project Portfolio & Multi-Deal Switcher',
            tab: 'documents',
            targetElementId: 'documents-header',
            targetSelector: '#documents-header, #project-portfolio',
            tag: 'Deal Repository',
            badge: 'Multi-Project',
            narrative: 'Manage all acquisition targets across your deal pipeline, switch between active deal rooms, and archive completed transactions.',
            keyTakeaway: 'Central hub for organizing and navigating deal workspaces.',
            cursorPlacement: 'top-left',
            durationMs: 7000,
        },
        {
            id: 'documents-step-2',
            num: 2,
            title: 'Verified Document Catalog & Status',
            tab: 'documents',
            targetElementId: 'documents-grid',
            targetSelector: '#documents-grid',
            tag: 'Document Vault',
            badge: 'VDR Catalog',
            narrative: 'Registry of all uploaded data room files with OCR completion status, extraction timestamps, file sizes, and document inclusion toggles.',
            keyTakeaway: 'Full control over active documents included in project synthesis.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'documents-step-3',
            num: 3,
            title: 'OCR Extraction & Evidence Drilldown',
            tab: 'documents',
            targetElementId: 'documents-grid',
            targetSelector: '#documents-grid',
            tag: 'Extraction Facts',
            badge: 'Line-Item Evidence',
            narrative: 'Drill into raw extracted table coordinates, OCR confidence scores, and line-item facts directly from source PDF documents.',
            keyTakeaway: 'Verify source citations with 100% ground-truth traceability.',
            cursorPlacement: 'bottom-left',
            durationMs: 7000,
        },
    ],
    shortcuts: [
        {
            id: 'shortcuts-step-1',
            num: 1,
            title: 'Power-User Keyboard Shortcuts Directory',
            tab: 'shortcuts',
            targetElementId: 'shortcuts-header',
            targetSelector: '#shortcuts-header',
            tag: 'Productivity',
            badge: 'Hotkeys Directory',
            narrative: 'Explore full keyboard navigation hotkeys: instant tab switching (1-9), Dillon AI deal copilot toggle (Cmd+K), and walkthrough controls.',
            keyTakeaway: 'Navigate the entire diligence platform with zero mouse friction.',
            cursorPlacement: 'top-left',
            durationMs: 7000,
        },
        {
            id: 'shortcuts-step-2',
            num: 2,
            title: 'Interactive Live Keyboard Simulator',
            tab: 'shortcuts',
            targetElementId: 'shortcuts-tester',
            targetSelector: '#shortcuts-tester',
            tag: 'Live Tester',
            badge: 'Key Lighting',
            narrative: 'Test hotkeys in real time with visual keyboard feedback highlighting active key combinations and command executions.',
            keyTakeaway: 'Interactive tool to practice and verify keyboard shortcuts.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'shortcuts-step-3',
            num: 3,
            title: 'Categorized Shortcuts Reference Cheatsheet',
            tab: 'shortcuts',
            targetElementId: 'shortcuts-hotkeys',
            targetSelector: '#shortcuts-hotkeys',
            tag: 'Cheatsheet',
            badge: 'Quick Reference',
            narrative: 'Categorized quick reference cards for Navigation, AI Copilot, Financial Modeling, and Guided Tours.',
            keyTakeaway: 'Handy cheat sheet for maximizing diligence workflow efficiency.',
            cursorPlacement: 'bottom-left',
            durationMs: 7000,
        },
    ],
    evals: [
        {
            id: 'evals-step-1',
            num: 1,
            title: 'Production Model Benchmark Comparison',
            tab: 'evals',
            targetElementId: 'evals-benchmarks',
            targetSelector: '#evals-benchmarks, [data-eval-benchmarks], [data-eval-header]',
            tag: 'AI Quality',
            badge: 'Model Benchmark',
            narrative: 'Empirical benchmark comparing extraction accuracy, table precision, and latency across OpenAI 5.6 Terra, OpenAI 5.6 Sol, and hybrid routing configurations.',
            keyTakeaway: 'Quantitative proof of zero-hallucination extraction accuracy.',
            cursorPlacement: 'top-left',
            durationMs: 7000,
        },
        {
            id: 'evals-step-2',
            num: 2,
            title: 'Track A Workflow Cost Analysis & Spend Drivers',
            tab: 'evals',
            targetElementId: 'eval-doc-breakdown',
            targetSelector: '[data-track-a-cost], #eval-doc-breakdown',
            tag: 'Cost Optimization',
            badge: '50%+ Cost Reduction',
            narrative: 'Empirical analysis identifying top workflow spend drivers and verifying >50% cost reductions via prompt caching and model routing.',
            keyTakeaway: 'Demonstrates enterprise-grade cost efficiency and architecture.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'evals-step-3',
            num: 3,
            title: 'Financial Extraction Accuracy Scorecards',
            tab: 'evals',
            targetElementId: 'eval-score-by-dimension',
            targetSelector: '#eval-score-by-dimension, #evals-accuracy',
            tag: 'Ground Truth',
            badge: 'Scorecard',
            narrative: 'Evaluates extraction precision across 500+ audited financial ground-truth items including revenue, EBITDA add-backs, and balance sheet accounts.',
            keyTakeaway: 'Verifies 100% benchmark pass rate across all deal types.',
            cursorPlacement: 'bottom-left',
            durationMs: 7000,
        },
    ],
    faqs: [
        {
            id: 'faqs-step-1',
            num: 1,
            title: 'Searchable Diligence Knowledge Base',
            tab: 'faqs',
            targetElementId: 'faqs-header',
            targetSelector: '#faqs-header, #faq-general',
            tag: 'Documentation',
            badge: 'Knowledge Base',
            narrative: 'Searchable encyclopedia covering SMB acquisition fundamentals, LOI mechanics, escrow holdback definitions, and working capital peg concepts.',
            keyTakeaway: 'Instant access to institutional M&A guidance and terminology.',
            cursorPlacement: 'top-left',
            durationMs: 7000,
        },
        {
            id: 'faqs-step-2',
            num: 2,
            title: 'Quality of Earnings & Financial Methodology',
            tab: 'faqs',
            targetElementId: 'faqs-header',
            targetSelector: '#faqs-header, #faq-methodology',
            tag: 'Financial Rules',
            badge: 'QoE & SBA',
            narrative: 'In-depth methodology documentation explaining discretionary add-back auditing standards, EBITDA normalization, and SBA 7(a) debt underwriting rules.',
            keyTakeaway: 'Clear explanation of the mathematical and accounting logic.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'faqs-step-3',
            num: 3,
            title: 'Platform Architecture & Best Practices',
            tab: 'faqs',
            targetElementId: 'faqs-header',
            targetSelector: '#faqs-header, #faq-troubleshooting',
            tag: 'Platform Guide',
            badge: 'Best Practices',
            narrative: 'Best practices for document preparation, OCR optimization, custom financial modeling, and AI copilot interactions.',
            keyTakeaway: 'Tips and tricks for getting the most out of the diligence platform.',
            cursorPlacement: 'bottom-left',
            durationMs: 7000,
        },
    ],
    history: [
        {
            id: 'history-step-1',
            num: 1,
            title: 'Chronological Audit Trail & Timestamps',
            tab: 'history',
            targetElementId: 'history-header',
            targetSelector: '#history-header',
            tag: 'Audit Trail',
            badge: 'Submission History',
            narrative: 'Immutable chronological record of every document upload, OCR parsing run, model update, and project synthesis execution.',
            keyTakeaway: 'Provides full audit compliance and user attribution.',
            cursorPlacement: 'top-left',
            durationMs: 7000,
        },
        {
            id: 'history-step-2',
            num: 2,
            title: 'Document Submission History Table',
            tab: 'history',
            targetElementId: 'history-table',
            targetSelector: '#history-table',
            tag: 'History Table',
            badge: 'Per-Doc Records',
            narrative: 'Interactive table with status indicators, environment toggles (Production / Test), extraction confidence scores, and retry actions.',
            keyTakeaway: 'Review and manage all historical document submissions.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'history-step-3',
            num: 3,
            title: 'Compliance & Version Ledger Review',
            tab: 'history',
            targetElementId: 'history-table',
            targetSelector: '#history-table',
            tag: 'Governance',
            badge: 'Compliance Ledger',
            narrative: 'Inspect historical AI responses, citation links, and raw extraction payloads for complete diligence auditability.',
            keyTakeaway: 'Audit-ready records for bank lenders and institutional LP reviews.',
            cursorPlacement: 'bottom-left',
            durationMs: 7000,
        },
    ],
    email: [
        {
            id: 'email-step-1',
            num: 1,
            title: 'Dynamic Broker Inquiry Templates',
            tab: 'email',
            targetElementId: 'email-header',
            targetSelector: '#email-header',
            tag: 'Outreach',
            badge: 'Email Templates',
            narrative: 'Ready-to-send email drafts populated with verified deal figures, asking multiples, and initial Phase I inquiry terms.',
            keyTakeaway: 'Accelerates broker correspondence with pre-formatted deal data.',
            cursorPlacement: 'top-left',
            durationMs: 7000,
        },
        {
            id: 'email-step-2',
            num: 2,
            title: 'Diligence Question Packet Composer',
            tab: 'email',
            targetElementId: 'email-editor',
            targetSelector: '#email-editor',
            tag: 'Email Composer',
            badge: 'Question Packets',
            narrative: 'Assemble customized management questionnaire emails directly from identified diligence red flags and add-back audit items.',
            keyTakeaway: 'Seamlessly converts diligence findings into management questions.',
            cursorPlacement: 'center',
            durationMs: 7000,
        },
        {
            id: 'email-step-3',
            num: 3,
            title: 'Outreach History & Follow-Up Tracking',
            tab: 'email',
            targetElementId: 'email-editor',
            targetSelector: '#email-editor',
            tag: 'Communication Log',
            badge: 'Follow-Up Tracker',
            narrative: 'Track outgoing broker emails, draft revisions, and follow-up schedules to ensure timely seller responses during diligence windows.',
            keyTakeaway: 'Keeps deal communications organized and on schedule.',
            cursorPlacement: 'bottom-left',
            durationMs: 7000,
        },
    ],
    errors: [
        {
            id: 'errors-step-1',
            num: 1,
            title: 'Workflow Error Log & Webhook Console',
            tab: 'errors',
            targetElementId: 'errors-header',
            targetSelector: '#errors-header, #workflow-errors',
            tag: 'Diagnostics',
            badge: 'Error Log',
            narrative: 'Real-time diagnostic log tracking OCR extraction failures, webhook timeouts, and API error codes with 1-click retry mechanisms.',
            keyTakeaway: 'Instant diagnostic feedback for pipeline troubleshooting.',
            cursorPlacement: 'top-left',
            durationMs: 7000,
        },
        {
            id: 'errors-step-2',
            num: 2,
            title: 'System Architecture & Infrastructure Health',
            tab: 'errors',
            targetElementId: 'errors-arch',
            targetSelector: '#errors-arch',
            tag: 'System Health',
            badge: 'Architecture',
            narrative: 'Visual architecture map illustrating n8n workflow connections, Supabase database synchronization, and LLM API endpoints.',
            keyTakeaway: 'Clear transparency into platform infrastructure and health.',
            cursorPlacement: 'bottom-left',
            durationMs: 7000,
        },
    ],
}

export function getTabTourPlaylist(tabId: WorkspaceTab): TourPlaylist {
    const playlistId = `tab-${tabId}`
    if (TOUR_PLAYLISTS[playlistId]) {
        return TOUR_PLAYLISTS[playlistId]
    }

    const dedicatedSteps = TAB_TOUR_STEPS[tabId]
    if (dedicatedSteps && dedicatedSteps.length > 0) {
        return {
            id: playlistId,
            title: `${tabId.charAt(0).toUpperCase() + tabId.slice(1)} Tab Guided Tour`,
            subtitle: `Targeted walkthrough for the ${tabId} workspace section`,
            durationLabel: `~${Math.max(1, Math.round(dedicatedSteps.length * 0.5))} min`,
            stepCount: dedicatedSteps.length,
            iconName: 'Compass',
            color: 'from-primary to-indigo-600',
            description: `A focused, step-by-step interactive tutorial for mastering the ${tabId} diligence section.`,
            steps: dedicatedSteps,
        }
    }

    // Default fallback single step if tab is ever unrecognized
    const defaultSteps: WalkthroughStep[] = [
        {
            id: `${tabId}-tour-step-1`,
            num: 1,
            title: `${tabId.charAt(0).toUpperCase() + tabId.slice(1)} Workspace Overview`,
            tab: tabId,
            targetElementId: 'deal-workspace',
            targetSelector: '#deal-workspace, main',
            tag: tabId.toUpperCase(),
            badge: 'Workspace',
            narrative: `Explore the ${tabId} workspace tools, tables, and audit controls to streamline your transaction analysis.`,
            keyTakeaway: `Dedicated section for institutional ${tabId} diligence.`,
            cursorPlacement: 'center',
            durationMs: 7000,
        },
    ]

    return {
        id: playlistId,
        title: `${tabId.charAt(0).toUpperCase() + tabId.slice(1)} Tab Tutorial`,
        subtitle: `Overview tutorial for the ${tabId} workspace`,
        durationLabel: '~30 sec',
        stepCount: defaultSteps.length,
        iconName: 'HelpCircle',
        color: 'from-primary to-indigo-600',
        description: `Explore key capabilities, tables, and outputs inside the ${tabId} section.`,
        steps: defaultSteps,
    }
}


