import type { TourPlaylist, WalkthroughStep } from './walkthroughTypes'

export const CORE_FAST_STEPS: WalkthroughStep[] = [
    {
        id: 'core-step-1',
        num: 1,
        title: 'Multi-Document Deal Intake & OCR',
        tab: 'diligence',
        targetElementId: 'project-intake',
        targetSelector: '[data-project-intake]',
        tag: 'Document Intake',
        badge: 'OCR & Parsing',
        narrative: 'Drop 2-year P&Ls, tax returns, signed LOIs, and teaser CIMs in one batch. Dillon AI isolates tables, balance sheets, and contractual covenants with zero data leakage.',
        keyTakeaway: 'Deterministic multi-file parser supporting PDF, Excel, and Word.',
        cursorPlacement: 'center',
        durationMs: 6500,
    },
    {
        id: 'core-step-2',
        num: 2,
        title: 'Deterministic Extraction & Fact Tracking',
        tab: 'diligence',
        targetElementId: 'project-intake',
        targetSelector: '[data-project-intake], #project-intake, #history-table',
        tag: 'Diligence Audit',
        badge: 'Audit Trail',
        narrative: 'Every uploaded file produces a verified financial fact sheet with exact line-item citations, OCR confidence levels, and version audit timestamps.',
        keyTakeaway: 'Zero numeric hallucination guarantee via strict per-doc extraction.',
        cursorPlacement: 'top-left',
        durationMs: 6500,
    },
    {
        id: 'core-step-3',
        num: 3,
        title: 'Deal-on-a-Page & Valuation Scorecard',
        tab: 'analysis',
        targetElementId: 'analysis-deal-on-a-page',
        targetSelector: '#analysis-deal-on-a-page, #analysis-scorecard, [data-deal-on-a-page]',
        tag: 'Executive Analysis',
        badge: 'Deal on a Page',
        narrative: 'Instantly view verified revenue, normalized EBITDA, debt sizing capacity, and target purchase multiple in a consolidated Investment Committee summary card.',
        keyTakeaway: 'Immediate single-pane executive summary with 100% auditable ground truth citations.',
        cursorPlacement: 'center',
        durationMs: 7000,
    },
    {
        id: 'core-step-4',
        num: 4,
        title: 'Valuation Gap & Multiple Disconnect Matrix',
        tab: 'valuation',
        targetElementId: 'valuation-comps',
        tag: 'Valuation',
        badge: 'Market Comps',
        narrative: 'Directly compares the seller asking multiple against empirical transaction comps across Bear (3.0x), Base (4.0x), and Bull (5.0x) valuation bands.',
        keyTakeaway: 'Highlights when a seller is asking 7.9x SDE against a 4.2x market ceiling.',
        cursorPlacement: 'center',
        durationMs: 6500,
    },
    {
        id: 'core-step-5',
        num: 5,
        title: 'Critical Red Flags & Solvency Diagnostics',
        tab: 'analysis',
        targetElementId: 'analysis-risk-valuation',
        tag: 'Risk Engine',
        badge: 'Red Flags',
        narrative: 'Synthesizes deal-killer risks including high customer concentration (>35%), thin debt service buffers, working capital deficits, and key-person dependency.',
        keyTakeaway: 'Instant PE traffic light grading (Green / Yellow / Red Flag).',
        cursorPlacement: 'center',
        durationMs: 7000,
    },
    {
        id: 'core-step-6',
        num: 6,
        title: 'Institutional IC Judgment & Escalation Verdict',
        tab: 'overview',
        targetElementId: 'synthesis-judgment',
        targetSelector: '#synthesis-judgment, [data-synthesis-judgment]',
        tag: 'Investment Committee',
        badge: 'Deal Verdict',
        narrative: 'Generates an Investment Committee verdict (PROCEED, RE-TRADE, or ESCALATE) with empirical valuation bridges and mitigation covenants.',
        keyTakeaway: 'Actionable executive synthesis for PE partners and search funds.',
        cursorPlacement: 'center',
        durationMs: 7000,
    },
    {
        id: 'core-step-7',
        num: 7,
        title: 'Dillon AI Interactive Deal Copilot',
        tab: 'overview',
        targetElementId: 'deal-chat-dock',
        targetSelector: 'button[title*="Chat"], [data-chat-trigger]',
        tag: 'AI Deal Copilot',
        badge: '3-Tier Routing',
        narrative: 'Ask natural-language questions about financial footnotes, lease commitments, customer churn, or general M&A terms with 1-click tab deep linking.',
        keyTakeaway: 'Grounds every AI answer directly in uploaded deal facts.',
        cursorPlacement: 'bottom-right',
        durationMs: 7000,
    },
    {
        id: 'core-step-8',
        num: 8,
        title: 'Remediation Playbook & Escrow Holdbacks',
        tab: 'negotiation',
        targetElementId: 'negotiation-levers',
        targetSelector: '#negotiation-levers, #analysis-term-sheet',
        tag: 'Negotiation',
        badge: 'Deal Terms',
        narrative: 'Converts identified red flags into contractual protections: $350k indemnity escrow holdbacks, 24-month seller note standstills, and broker pushback scripts.',
        keyTakeaway: 'Arm your deal team with battle-tested negotiation terms.',
        cursorPlacement: 'center',
        durationMs: 6500,
    },
    {
        id: 'core-step-9',
        num: 9,
        title: 'Capital Structure, DSCR & Equity Waterfall',
        tab: 'structure',
        targetElementId: 'structure-dscr',
        targetSelector: '#structure-dscr, #returns-waterfall',
        tag: 'Capital Stack',
        badge: 'Debt Sizing & IRR',
        narrative: 'Simulate Senior SBA 7(a) debt amortization, seller note mezzanine tranches, buyer cash equity, and 5-year levered IRR returns under downside scenarios.',
        keyTakeaway: 'Instant debt service coverage verification (Target DSCR ≥ 1.35x).',
        cursorPlacement: 'center',
        durationMs: 7000,
    },
    {
        id: 'core-step-10',
        num: 10,
        title: '1-Click IC Memo Export & Live Cloud Engine',
        tab: 'overview',
        targetElementId: 'export-deal-btn',
        targetSelector: 'button:has(svg.lucide-file-text), [data-export-btn]',
        tag: 'IC Memo Export',
        badge: 'Publication Ready',
        narrative: 'Download publication-ready Investment Committee memorandums and audit-grade deal packages, powered by enterprise n8n and Supabase cloud workflows.',
        keyTakeaway: '100% audit transparency ready for lenders and investment committees.',
        cursorPlacement: 'top-right',
        durationMs: 7000,
    },
]

export const DEEP_DIVE_STEPS: WalkthroughStep[] = [
    {
        id: 'deep-step-1',
        num: 1,
        title: 'Multi-Doc Deal Room Ingestion',
        tab: 'diligence',
        targetElementId: 'project-intake',
        targetSelector: '[data-project-intake]',
        tag: 'Intake',
        badge: 'Deal Room',
        narrative: 'Upload CIMs, signed LOIs, 2-year tax returns, and QuickBooks balance sheets simultaneously into the secure isolated intake vault.',
        keyTakeaway: 'Multi-file parallel queue with auto-detected document classification.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-2',
        num: 2,
        title: 'Deterministic OCR & Extraction Pipeline',
        tab: 'diligence',
        targetElementId: 'project-intake',
        targetSelector: '[data-project-intake]',
        tag: 'Ingestion',
        badge: 'Multi-Model AI',
        narrative: 'Our multi-model extraction pipeline parses scanned PDFs and multi-tab spreadsheets into structured JSON schemas with full cell coordinate mapping.',
        keyTakeaway: 'Per-document extraction primary model powered by Claude 3.5 / Sonnet.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-3',
        num: 3,
        title: 'Submission History & Version Audit Trail',
        tab: 'history',
        targetElementId: 'history-table',
        tag: 'Audit Trail',
        badge: 'Provenance',
        narrative: 'Inspect all historical document versions, extraction processing times, tokens consumed, and extraction status across all deal runs.',
        keyTakeaway: 'Full chronological ledger for every document run.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-4',
        num: 4,
        title: 'LOI Terms & Purchase Price Extraction',
        tab: 'analysis',
        targetElementId: 'analysis-deal-on-a-page',
        tag: 'LOI Terms',
        badge: 'Core Terms',
        narrative: 'Extracts purchase price, earnout milestones, seller financing rates, and closing contingencies directly from the executed Letter of Intent.',
        keyTakeaway: 'Locks in agreed baseline terms vs seller marketing teasers.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-5',
        num: 5,
        title: '100% Ground Truth Evidence & Citations',
        tab: 'analysis',
        targetElementId: 'analysis-scorecard',
        tag: 'Citations',
        badge: 'Ground Truth',
        narrative: 'Every single extracted financial metric links directly to its source document, page number, and original table bounding box.',
        keyTakeaway: 'Click any metric in the workspace to inspect its underlying document proof.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-6',
        num: 6,
        title: 'Verified SDE & EBITDA Add-Backs',
        tab: 'analysis',
        targetElementId: 'analysis-qoe',
        tag: 'Quality of Earnings',
        badge: 'QoE Adjustments',
        narrative: 'Reconciles discretionary expenses, non-arm’s-length officer salaries, and one-time consulting fees against IRS guidelines.',
        keyTakeaway: 'Separates confirmed add-backs from unsubstantiated seller claims.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-7',
        num: 7,
        title: 'Enterprise Value Implied by Asking Price',
        tab: 'valuation',
        targetElementId: 'valuation-comps',
        tag: 'Valuation',
        badge: 'Implied Multiple',
        narrative: 'Calculates headline Enterprise Value multiple against normalized earnings and contrasts it against actual lower-middle-market deal comps.',
        keyTakeaway: 'Instantly surfaces seller premium over historical sector transactions.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-8',
        num: 8,
        title: 'Debt-to-Asset & Solvency Audit',
        tab: 'analysis',
        targetElementId: 'analysis-snapshot',
        tag: 'Balance Sheet',
        badge: 'Solvency Health',
        narrative: 'Cross-checks balance sheet current assets against funded obligations to ensure the target business is liquid and solvent.',
        keyTakeaway: 'Verifies healthy debt-to-asset ratios before committing lender capital.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-9',
        num: 9,
        title: 'Cross-Document Contradiction Reconciliation',
        tab: 'analysis',
        targetElementId: 'analysis-coverage',
        tag: 'Reconciliation',
        badge: 'Contradiction Detector',
        narrative: 'Identifies discrepancies between broker teaser decks and audited tax returns (e.g. $4.8M reported revenue vs $4.2M on IRS 1120-S).',
        keyTakeaway: 'Surfaces hidden variance before entering formal exclusivity.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-10',
        num: 10,
        title: 'Customer Concentration Red Flag Analysis',
        tab: 'analysis',
        targetElementId: 'analysis-risk-valuation',
        tag: 'Risk Analysis',
        badge: 'Customer Concentration',
        narrative: 'Evaluates top customer revenue share. Deals with top-client concentration over 30% are flagged for escrow indemnity and earnout restructuring.',
        keyTakeaway: 'Calculates maximum single-point-of-failure revenue risk.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-11',
        num: 11,
        title: 'Cross-Doc Synthesis & $350k Escrow Holdback',
        tab: 'overview',
        targetElementId: 'synthesis-judgment',
        tag: 'Synthesis',
        badge: 'Holdback Engine',
        narrative: 'Multi-document synthesis engine computes specific contractual dollar holdbacks (e.g., $350,000 indemnification holdback for 18 months).',
        keyTakeaway: 'Translates analytical risk into enforceable purchase agreement clauses.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-12',
        num: 12,
        title: 'Key Management Diligence Questions',
        tab: 'overview',
        targetElementId: 'synthesis-next-step',
        tag: 'Management Q&A',
        badge: 'Management Interview',
        narrative: 'Auto-generates high-leverage confirmatory questions tailored for management interviews on vendor contracts and customer churn.',
        keyTakeaway: 'Empowers buyers with senior diligence interview scripts.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-13',
        num: 13,
        title: 'Critical Cash Flow & Margin Pressure Alerts',
        tab: 'overview',
        targetElementId: 'synthesis-valuation',
        tag: 'Cash Flow',
        badge: 'Margin Degradation',
        narrative: 'Alerts the deal team to gross margin compression or working capital seasonality that could impair debt service post-acquisition.',
        keyTakeaway: 'Early warning engine against post-close liquidity crunches.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-14',
        num: 14,
        title: 'Investment Committee ESCALATE Verdict',
        tab: 'overview',
        targetElementId: 'synthesis-judgment',
        tag: 'Verdict',
        badge: 'Committee Summary',
        narrative: 'Packages all red flags, multiple disconnects, and normalized EBITDA into an institutional PE summary verdict for deal partners.',
        keyTakeaway: 'Clear GO / NO-GO / RE-TRADE recommendation.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-15',
        num: 15,
        title: 'Enterprise Value Methodologies & Bridge',
        tab: 'valuation',
        targetElementId: 'valuation-comps',
        tag: 'Valuation Bridge',
        badge: 'EV Mechanics',
        narrative: 'Examines Enterprise Value calculation mechanics: EV = Headline Purchase Price + Net Funded Debt − Closing Cash.',
        keyTakeaway: 'Unpacks exact debt and cash adjustments across all scenarios.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-16',
        num: 16,
        title: 'Normalized Valuation Multiples Breakdown',
        tab: 'valuation',
        targetElementId: 'valuation-comps',
        tag: 'Multiples Matrix',
        badge: 'Bear / Base / Bull',
        narrative: 'Models dynamic valuation sensitivity across 3.0x Bear, 4.0x Base, and 5.0x Bull multiples based on target company quality.',
        keyTakeaway: 'Determines downside floor and upside potential before bidding.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-17',
        num: 17,
        title: 'Breakeven Analysis & Fixed Cost Absorption',
        tab: 'analysis',
        targetElementId: 'analysis-breakeven',
        tag: 'Breakeven',
        badge: 'Fixed vs Variable',
        narrative: 'Calculates the exact revenue breakeven threshold and margin of safety required to cover operating overhead and debt service.',
        keyTakeaway: 'Answers: How much can revenue drop before the business loses money?',
        durationMs: 6500,
    },
    {
        id: 'deep-step-18',
        num: 18,
        title: 'Monte Carlo Simulation (1,000 Iterations)',
        tab: 'analysis',
        targetElementId: 'analysis-monte-carlo',
        tag: 'Monte Carlo',
        badge: 'Stochastic Simulation',
        narrative: 'Simulates 1,000 stochastic economic outcomes across revenue growth, margin volatility, and exit multiples to compute probability of loss.',
        keyTakeaway: 'Rigorous risk quantification beyond simple static models.',
        durationMs: 7000,
    },
    {
        id: 'deep-step-19',
        num: 19,
        title: 'Opportunity & Revenue Upside Levers',
        tab: 'growth',
        targetElementId: 'growth-scenarios',
        targetSelector: '#growth-scenarios, #analysis-opportunity',
        tag: 'Growth Plan',
        badge: 'Value Creation',
        narrative: 'Identifies post-acquisition value creation opportunities: pricing power adjustments, sales team expansion, and cross-selling.',
        keyTakeaway: 'Clear 100-day operational roadmap to expand equity value.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-20',
        num: 20,
        title: 'Dillon AI Deal Copilot Context Integration',
        tab: 'overview',
        targetElementId: 'deal-chat-dock',
        targetSelector: 'button[title*="Chat"], [data-chat-trigger]',
        tag: 'Deal Copilot',
        badge: 'AI Assistant',
        narrative: 'Dillon AI ingests the full workspace financial model, OCR citations, and red flags into its active system prompt for real-time intelligence.',
        keyTakeaway: 'Zero generic hallucinations — every answer cites live project facts.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-21',
        num: 21,
        title: 'Grounded Copilot Deal Q&A & Calculations',
        tab: 'overview',
        targetElementId: 'deal-chat-dock',
        targetSelector: 'button[title*="Chat"], [data-chat-trigger]',
        tag: 'Copilot Q&A',
        badge: 'Deep Linking',
        narrative: 'Ask complex questions like: "What is the DSCR under a 10.5% interest rate?" or "Where is the breakeven chart?" with instant deep links.',
        keyTakeaway: 'Interactive AI answers with 1-click workspace navigation links.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-22',
        num: 22,
        title: '1-Click Broker Negotiation & Pushback Scripts',
        tab: 'negotiation',
        targetElementId: 'negotiation-levers',
        targetSelector: '#negotiation-levers, #analysis-term-sheet',
        tag: 'Broker Scripts',
        badge: 'Email Generator',
        narrative: 'Generates polite, professional broker pushback letters highlighting valuation gaps and asking for detailed customer concentration schedules.',
        keyTakeaway: 'Instant negotiation leverage backed by empirical findings.',
        durationMs: 6000,
    },
    {
        id: 'deep-step-23',
        num: 23,
        title: 'Senior Debt Sizing & SBA 7(a) Limits',
        tab: 'structure',
        targetElementId: 'structure-dscr',
        targetSelector: '#structure-dscr, #structure-sources-uses',
        tag: 'Senior Debt',
        badge: 'SBA 7(a) Modeling',
        narrative: 'Models maximum $5.0M SBA 7(a) senior debt limits, 10-year amortization curves, and current prime-plus interest rate assumptions.',
        keyTakeaway: 'Ensures deal structure complies with SBA lending standards.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-24',
        num: 24,
        title: 'Seller Note Subordination & Standstill Terms',
        tab: 'structure',
        targetElementId: 'structure-sources-uses',
        targetSelector: '#structure-sources-uses, #returns-waterfall',
        tag: 'Seller Note',
        badge: 'Subordination',
        narrative: 'Structures a 10% to 15% seller promissory note with a 24-month payment standstill to qualify for SBA equity injection rules.',
        keyTakeaway: 'Bridges valuation gaps while minimizing buyer cash out of pocket.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-25',
        num: 25,
        title: 'Working Capital Peg & Closing True-Up Rules',
        tab: 'analysis',
        targetElementId: 'analysis-rules',
        targetSelector: '#analysis-rules, #analysis-snapshot',
        tag: 'Working Capital',
        badge: 'Peg Definition',
        narrative: 'Defines the Target Net Working Capital (NWC) Peg based on 12-month trailing averages to prevent seller cash stripping before closing.',
        keyTakeaway: 'Prevents post-closing disputes over accounts receivable and inventory.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-26',
        num: 26,
        title: '5-Year Levered Equity Waterfall & IRR Matrix',
        tab: 'returns',
        targetElementId: 'returns-waterfall',
        targetSelector: '#returns-waterfall, #returns-irr',
        tag: 'Returns Waterfall',
        badge: 'IRR & MOIC',
        narrative: 'Models 5-year levered equity returns, cash-on-cash yield, debt paydown equity buildup, and exit multiples to calculate final investor IRR.',
        keyTakeaway: 'Institutional returns analysis for PE sponsors and search funds.',
        durationMs: 7000,
    },
    {
        id: 'deep-step-27',
        num: 27,
        title: 'Phase II Due Diligence Confirmatory Checklist',
        tab: 'diagnostics',
        targetElementId: 'checklist-section',
        targetSelector: '#checklist-section, #analysis-coverage',
        tag: 'Checklist',
        badge: 'Confirmatory DD',
        narrative: 'Generates a 30-item customized diligence request list (Phase II DD) covering tax compliance, key employee agreements, and IP assignments.',
        keyTakeaway: 'Exhaustive legal and financial verification before definitive signing.',
        durationMs: 6500,
    },
    {
        id: 'deep-step-28',
        num: 28,
        title: 'Publication-Ready IC Memo & Full Export',
        tab: 'overview',
        targetElementId: 'export-deal-btn',
        targetSelector: 'button:has(svg.lucide-file-text), [data-export-btn]',
        tag: 'IC Memo Export',
        badge: 'Final Deliverable',
        narrative: 'Export complete audit packages and Investment Committee memos in markdown and PDF formats with full chart snapshots and provenance tags.',
        keyTakeaway: 'Professional, defensible diligence ready for institutional signoff.',
        durationMs: 7000,
    },
]

export const QUEST_MISSIONS: WalkthroughStep[] = [
    {
        id: 'quest-step-1',
        num: 1,
        title: 'Mission 1: The Valuation Gap Detective',
        tab: 'valuation',
        targetElementId: 'valuation-comps',
        tag: 'Quest 1',
        badge: 'Valuation Detective',
        narrative: 'The seller is asking for $5.0M, which represents a 7.9x multiple on reported earnings. Market comps for this sector top out at 4.2x.',
        keyTakeaway: 'Explore the valuation band and observe the implied discount.',
        questPrompt: {
            instruction: 'Switch to the Valuation tab and review the Bear vs Base vs Bull multiple spread.',
            hint: 'Click on the Valuation tab in the top navigation bar.',
            triggerType: 'tab_change',
            expectedValue: 'valuation',
        },
        durationMs: 12000,
    },
    {
        id: 'quest-step-2',
        num: 2,
        title: 'Mission 2: Inspecting QoE Add-Backs',
        tab: 'analysis',
        targetElementId: 'analysis-qoe',
        tag: 'Quest 2',
        badge: 'QoE Auditor',
        narrative: 'The seller claimed $142k in discretionary adjustments. Inspect the Quality of Earnings table to identify unverified items.',
        keyTakeaway: 'Verify owner compensation and discretionary expenses.',
        questPrompt: {
            instruction: 'Navigate to the Analysis tab to examine the Quality of Earnings breakdown.',
            hint: 'Click the Analysis tab to view the EBITDA reconciliation table.',
            triggerType: 'tab_change',
            expectedValue: 'analysis',
        },
        durationMs: 12000,
    },
    {
        id: 'quest-step-3',
        num: 3,
        title: 'Mission 3: Testing Debt Service Coverage',
        tab: 'structure',
        targetElementId: 'structure-dscr',
        targetSelector: '#structure-dscr, #returns-waterfall',
        tag: 'Quest 3',
        badge: 'Lender Sizing',
        narrative: 'Lenders require a minimum DSCR of 1.25x. At 1.38x, this deal meets Senior SBA guidelines with a modest safety cushion.',
        keyTakeaway: 'Check debt service coverage under various interest rate assumptions.',
        questPrompt: {
            instruction: 'Navigate to Deal Structure to inspect the DSCR coverage ratio.',
            hint: 'Click on Deal Structure in the top navigation bar.',
            triggerType: 'tab_change',
            expectedValue: 'structure',
        },
        durationMs: 12000,
    },
    {
        id: 'quest-step-4',
        num: 4,
        title: 'Mission 4: Interrogating Dillon AI Copilot',
        tab: 'overview',
        targetElementId: 'deal-chat-dock',
        targetSelector: 'button[title*="Chat"], [data-chat-trigger]',
        tag: 'Quest 4',
        badge: 'AI Investigator',
        narrative: 'Dillon AI is connected to all uploaded deal documents and models. Ask any diligence question or ask for an executive deal memo.',
        keyTakeaway: 'Use natural-language prompts to uncover risks and draft emails.',
        questPrompt: {
            instruction: 'Open the Dillon AI Deal Copilot panel on the right side of the screen.',
            hint: 'Click the Dillon AI Chat button in the bottom-right corner.',
            triggerType: 'click_target',
        },
        durationMs: 12000,
    },
    {
        id: 'quest-step-5',
        num: 5,
        title: 'Mission 5: Exporting the Investment Memo',
        tab: 'overview',
        targetElementId: 'export-deal-btn',
        targetSelector: 'button:has(svg.lucide-file-text), [data-export-btn]',
        tag: 'Quest 5',
        badge: 'Deal Closer',
        narrative: 'Congratulations! You have inspected the deal terms, validated the earnings, and evaluated debt sizing. You are ready to export the deal packet.',
        keyTakeaway: '1-click export for partners, lenders, and investment committees.',
        questPrompt: {
            instruction: 'Review the Export Deal button in the top header to see export options.',
            hint: 'Look for Export Deal in the top-right header.',
            triggerType: 'tab_change',
            expectedValue: 'overview',
        },
        durationMs: 12000,
    },
]

export const TOUR_PLAYLISTS: Record<string, TourPlaylist> = {
    'core-fast': {
        id: 'core-fast',
        title: '10-Step Core Diligence Tour',
        subtitle: 'Fast-track executive overview (~90 seconds)',
        durationLabel: '~90 sec',
        stepCount: CORE_FAST_STEPS.length,
        iconName: 'Zap',
        color: 'from-blue-600 to-indigo-600',
        description: 'Covers the essential end-to-end M&A diligence pipeline from multi-document ingestion and OCR to EBITDA adjustments, valuation gaps, and IC memos.',
        steps: CORE_FAST_STEPS,
    },
    'deep-dive': {
        id: 'deep-dive',
        title: '28-Step Full Pipeline Deep Dive',
        subtitle: 'Institutional PE diligence masterclass (~3-4 mins)',
        durationLabel: '~3.5 min',
        stepCount: DEEP_DIVE_STEPS.length,
        iconName: 'Layers',
        color: 'from-emerald-600 to-teal-600',
        description: 'An exhaustive, step-by-step masterclass inspecting every tab, solvency test, customer concentration metric, Monte Carlo sim, tax schedule, and Phase II checklist.',
        steps: DEEP_DIVE_STEPS,
    },
    'interactive-quest': {
        id: 'interactive-quest',
        title: 'Interactive Hands-On Tutorial',
        subtitle: 'Gamified diligence missions (learn by doing)',
        durationLabel: 'Self-Paced',
        stepCount: QUEST_MISSIONS.length,
        iconName: 'Target',
        color: 'from-amber-500 to-orange-600',
        description: 'Interactive quest mode with real hands-on missions. Complete each challenge to master valuation modeling, add-back audits, and deal negotiation.',
        steps: QUEST_MISSIONS,
    },
}
